// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module krnl_LZW_krnl_LZW_entry4 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        input_r,
        input_length,
        send_data,
        output_length,
        input_out_din,
        input_out_full_n,
        input_out_write,
        input_length_out_din,
        input_length_out_full_n,
        input_length_out_write,
        send_data_out_din,
        send_data_out_full_n,
        send_data_out_write,
        send_data_out1_din,
        send_data_out1_full_n,
        send_data_out1_write,
        output_length_out_din,
        output_length_out_full_n,
        output_length_out_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] input_r;
input  [63:0] input_length;
input  [63:0] send_data;
input  [63:0] output_length;
output  [63:0] input_out_din;
input   input_out_full_n;
output   input_out_write;
output  [63:0] input_length_out_din;
input   input_length_out_full_n;
output   input_length_out_write;
output  [63:0] send_data_out_din;
input   send_data_out_full_n;
output   send_data_out_write;
output  [63:0] send_data_out1_din;
input   send_data_out1_full_n;
output   send_data_out1_write;
output  [63:0] output_length_out_din;
input   output_length_out_full_n;
output   output_length_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg input_out_write;
reg input_length_out_write;
reg send_data_out_write;
reg send_data_out1_write;
reg output_length_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    input_out_blk_n;
reg    input_length_out_blk_n;
reg    send_data_out_blk_n;
reg    send_data_out1_blk_n;
reg    output_length_out_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((real_start == 1'b0) | (output_length_out_full_n == 1'b0) | (send_data_out1_full_n == 1'b0) | (send_data_out_full_n == 1'b0) | (input_length_out_full_n == 1'b0) | (input_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (output_length_out_full_n == 1'b0) | (send_data_out1_full_n == 1'b0) | (send_data_out_full_n == 1'b0) | (input_length_out_full_n == 1'b0) | (input_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        input_length_out_blk_n = input_length_out_full_n;
    end else begin
        input_length_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (output_length_out_full_n == 1'b0) | (send_data_out1_full_n == 1'b0) | (send_data_out_full_n == 1'b0) | (input_length_out_full_n == 1'b0) | (input_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        input_length_out_write = 1'b1;
    end else begin
        input_length_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        input_out_blk_n = input_out_full_n;
    end else begin
        input_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (output_length_out_full_n == 1'b0) | (send_data_out1_full_n == 1'b0) | (send_data_out_full_n == 1'b0) | (input_length_out_full_n == 1'b0) | (input_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        input_out_write = 1'b1;
    end else begin
        input_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (output_length_out_full_n == 1'b0) | (send_data_out1_full_n == 1'b0) | (send_data_out_full_n == 1'b0) | (input_length_out_full_n == 1'b0) | (input_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        output_length_out_blk_n = output_length_out_full_n;
    end else begin
        output_length_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (output_length_out_full_n == 1'b0) | (send_data_out1_full_n == 1'b0) | (send_data_out_full_n == 1'b0) | (input_length_out_full_n == 1'b0) | (input_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        output_length_out_write = 1'b1;
    end else begin
        output_length_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        send_data_out1_blk_n = send_data_out1_full_n;
    end else begin
        send_data_out1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (output_length_out_full_n == 1'b0) | (send_data_out1_full_n == 1'b0) | (send_data_out_full_n == 1'b0) | (input_length_out_full_n == 1'b0) | (input_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        send_data_out1_write = 1'b1;
    end else begin
        send_data_out1_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        send_data_out_blk_n = send_data_out_full_n;
    end else begin
        send_data_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (output_length_out_full_n == 1'b0) | (send_data_out1_full_n == 1'b0) | (send_data_out_full_n == 1'b0) | (input_length_out_full_n == 1'b0) | (input_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        send_data_out_write = 1'b1;
    end else begin
        send_data_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (output_length_out_full_n == 1'b0) | (send_data_out1_full_n == 1'b0) | (send_data_out_full_n == 1'b0) | (input_length_out_full_n == 1'b0) | (input_out_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign input_length_out_din = input_length;

assign input_out_din = input_r;

assign output_length_out_din = output_length;

assign send_data_out1_din = send_data;

assign send_data_out_din = send_data;

assign start_out = real_start;

endmodule //krnl_LZW_krnl_LZW_entry4
