-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity krnl_LZW_dataflow_in_loop_VITIS_LOOP_346_2_entry6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    input_r_empty_n : IN STD_LOGIC;
    input_r_read : OUT STD_LOGIC;
    send_data_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    send_data_empty_n : IN STD_LOGIC;
    send_data_read : OUT STD_LOGIC;
    i_1_dout : IN STD_LOGIC_VECTOR (6 downto 0);
    i_1_empty_n : IN STD_LOGIC;
    i_1_read : OUT STD_LOGIC;
    output_length_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    output_length_empty_n : IN STD_LOGIC;
    output_length_read : OUT STD_LOGIC;
    input_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    input_out_full_n : IN STD_LOGIC;
    input_out_write : OUT STD_LOGIC;
    send_data_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    send_data_out_full_n : IN STD_LOGIC;
    send_data_out_write : OUT STD_LOGIC;
    i_1_out_din : OUT STD_LOGIC_VECTOR (6 downto 0);
    i_1_out_full_n : IN STD_LOGIC;
    i_1_out_write : OUT STD_LOGIC;
    output_length_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_length_out_full_n : IN STD_LOGIC;
    output_length_out_write : OUT STD_LOGIC );
end;


architecture behav of krnl_LZW_dataflow_in_loop_VITIS_LOOP_346_2_entry6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal input_r_blk_n : STD_LOGIC;
    signal send_data_blk_n : STD_LOGIC;
    signal i_1_blk_n : STD_LOGIC;
    signal output_length_blk_n : STD_LOGIC;
    signal input_out_blk_n : STD_LOGIC;
    signal send_data_out_blk_n : STD_LOGIC;
    signal i_1_out_blk_n : STD_LOGIC;
    signal output_length_out_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (output_length_out_full_n = ap_const_logic_0) or (i_1_out_full_n = ap_const_logic_0) or (send_data_out_full_n = ap_const_logic_0) or (input_out_full_n = ap_const_logic_0) or (output_length_empty_n = ap_const_logic_0) or (i_1_empty_n = ap_const_logic_0) or (send_data_empty_n = ap_const_logic_0) or (input_r_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, input_r_empty_n, send_data_empty_n, i_1_empty_n, output_length_empty_n, input_out_full_n, send_data_out_full_n, i_1_out_full_n, output_length_out_full_n)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, input_r_empty_n, send_data_empty_n, i_1_empty_n, output_length_empty_n, input_out_full_n, send_data_out_full_n, i_1_out_full_n, output_length_out_full_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (output_length_out_full_n = ap_const_logic_0) or (i_1_out_full_n = ap_const_logic_0) or (send_data_out_full_n = ap_const_logic_0) or (input_out_full_n = ap_const_logic_0) or (output_length_empty_n = ap_const_logic_0) or (i_1_empty_n = ap_const_logic_0) or (send_data_empty_n = ap_const_logic_0) or (input_r_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, input_r_empty_n, send_data_empty_n, i_1_empty_n, output_length_empty_n, input_out_full_n, send_data_out_full_n, i_1_out_full_n, output_length_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_length_out_full_n = ap_const_logic_0) or (i_1_out_full_n = ap_const_logic_0) or (send_data_out_full_n = ap_const_logic_0) or (input_out_full_n = ap_const_logic_0) or (output_length_empty_n = ap_const_logic_0) or (i_1_empty_n = ap_const_logic_0) or (send_data_empty_n = ap_const_logic_0) or (input_r_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, input_r_empty_n, send_data_empty_n, i_1_empty_n, output_length_empty_n, input_out_full_n, send_data_out_full_n, i_1_out_full_n, output_length_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_length_out_full_n = ap_const_logic_0) or (i_1_out_full_n = ap_const_logic_0) or (send_data_out_full_n = ap_const_logic_0) or (input_out_full_n = ap_const_logic_0) or (output_length_empty_n = ap_const_logic_0) or (i_1_empty_n = ap_const_logic_0) or (send_data_empty_n = ap_const_logic_0) or (input_r_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    i_1_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, i_1_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            i_1_blk_n <= i_1_empty_n;
        else 
            i_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    i_1_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, i_1_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            i_1_out_blk_n <= i_1_out_full_n;
        else 
            i_1_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    i_1_out_din <= i_1_dout;

    i_1_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, input_r_empty_n, send_data_empty_n, i_1_empty_n, output_length_empty_n, input_out_full_n, send_data_out_full_n, i_1_out_full_n, output_length_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_length_out_full_n = ap_const_logic_0) or (i_1_out_full_n = ap_const_logic_0) or (send_data_out_full_n = ap_const_logic_0) or (input_out_full_n = ap_const_logic_0) or (output_length_empty_n = ap_const_logic_0) or (i_1_empty_n = ap_const_logic_0) or (send_data_empty_n = ap_const_logic_0) or (input_r_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            i_1_out_write <= ap_const_logic_1;
        else 
            i_1_out_write <= ap_const_logic_0;
        end if; 
    end process;


    i_1_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, input_r_empty_n, send_data_empty_n, i_1_empty_n, output_length_empty_n, input_out_full_n, send_data_out_full_n, i_1_out_full_n, output_length_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_length_out_full_n = ap_const_logic_0) or (i_1_out_full_n = ap_const_logic_0) or (send_data_out_full_n = ap_const_logic_0) or (input_out_full_n = ap_const_logic_0) or (output_length_empty_n = ap_const_logic_0) or (i_1_empty_n = ap_const_logic_0) or (send_data_empty_n = ap_const_logic_0) or (input_r_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            i_1_read <= ap_const_logic_1;
        else 
            i_1_read <= ap_const_logic_0;
        end if; 
    end process;


    input_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, input_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_out_blk_n <= input_out_full_n;
        else 
            input_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_out_din <= input_r_dout;

    input_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, input_r_empty_n, send_data_empty_n, i_1_empty_n, output_length_empty_n, input_out_full_n, send_data_out_full_n, i_1_out_full_n, output_length_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_length_out_full_n = ap_const_logic_0) or (i_1_out_full_n = ap_const_logic_0) or (send_data_out_full_n = ap_const_logic_0) or (input_out_full_n = ap_const_logic_0) or (output_length_empty_n = ap_const_logic_0) or (i_1_empty_n = ap_const_logic_0) or (send_data_empty_n = ap_const_logic_0) or (input_r_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_out_write <= ap_const_logic_1;
        else 
            input_out_write <= ap_const_logic_0;
        end if; 
    end process;


    input_r_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, input_r_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_r_blk_n <= input_r_empty_n;
        else 
            input_r_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    input_r_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, input_r_empty_n, send_data_empty_n, i_1_empty_n, output_length_empty_n, input_out_full_n, send_data_out_full_n, i_1_out_full_n, output_length_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_length_out_full_n = ap_const_logic_0) or (i_1_out_full_n = ap_const_logic_0) or (send_data_out_full_n = ap_const_logic_0) or (input_out_full_n = ap_const_logic_0) or (output_length_empty_n = ap_const_logic_0) or (i_1_empty_n = ap_const_logic_0) or (send_data_empty_n = ap_const_logic_0) or (input_r_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_r_read <= ap_const_logic_1;
        else 
            input_r_read <= ap_const_logic_0;
        end if; 
    end process;


    output_length_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_length_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            output_length_blk_n <= output_length_empty_n;
        else 
            output_length_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    output_length_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_length_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            output_length_out_blk_n <= output_length_out_full_n;
        else 
            output_length_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    output_length_out_din <= output_length_dout;

    output_length_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, input_r_empty_n, send_data_empty_n, i_1_empty_n, output_length_empty_n, input_out_full_n, send_data_out_full_n, i_1_out_full_n, output_length_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_length_out_full_n = ap_const_logic_0) or (i_1_out_full_n = ap_const_logic_0) or (send_data_out_full_n = ap_const_logic_0) or (input_out_full_n = ap_const_logic_0) or (output_length_empty_n = ap_const_logic_0) or (i_1_empty_n = ap_const_logic_0) or (send_data_empty_n = ap_const_logic_0) or (input_r_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            output_length_out_write <= ap_const_logic_1;
        else 
            output_length_out_write <= ap_const_logic_0;
        end if; 
    end process;


    output_length_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, input_r_empty_n, send_data_empty_n, i_1_empty_n, output_length_empty_n, input_out_full_n, send_data_out_full_n, i_1_out_full_n, output_length_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_length_out_full_n = ap_const_logic_0) or (i_1_out_full_n = ap_const_logic_0) or (send_data_out_full_n = ap_const_logic_0) or (input_out_full_n = ap_const_logic_0) or (output_length_empty_n = ap_const_logic_0) or (i_1_empty_n = ap_const_logic_0) or (send_data_empty_n = ap_const_logic_0) or (input_r_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            output_length_read <= ap_const_logic_1;
        else 
            output_length_read <= ap_const_logic_0;
        end if; 
    end process;


    send_data_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, send_data_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            send_data_blk_n <= send_data_empty_n;
        else 
            send_data_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    send_data_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, send_data_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            send_data_out_blk_n <= send_data_out_full_n;
        else 
            send_data_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    send_data_out_din <= send_data_dout;

    send_data_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, input_r_empty_n, send_data_empty_n, i_1_empty_n, output_length_empty_n, input_out_full_n, send_data_out_full_n, i_1_out_full_n, output_length_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_length_out_full_n = ap_const_logic_0) or (i_1_out_full_n = ap_const_logic_0) or (send_data_out_full_n = ap_const_logic_0) or (input_out_full_n = ap_const_logic_0) or (output_length_empty_n = ap_const_logic_0) or (i_1_empty_n = ap_const_logic_0) or (send_data_empty_n = ap_const_logic_0) or (input_r_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            send_data_out_write <= ap_const_logic_1;
        else 
            send_data_out_write <= ap_const_logic_0;
        end if; 
    end process;


    send_data_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, input_r_empty_n, send_data_empty_n, i_1_empty_n, output_length_empty_n, input_out_full_n, send_data_out_full_n, i_1_out_full_n, output_length_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_length_out_full_n = ap_const_logic_0) or (i_1_out_full_n = ap_const_logic_0) or (send_data_out_full_n = ap_const_logic_0) or (input_out_full_n = ap_const_logic_0) or (output_length_empty_n = ap_const_logic_0) or (i_1_empty_n = ap_const_logic_0) or (send_data_empty_n = ap_const_logic_0) or (input_r_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            send_data_read <= ap_const_logic_1;
        else 
            send_data_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
