// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module LZW_hybrid_hash_HW_my_hash (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        key,
        ap_return
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [20:0] key;
output  [14:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] hashed_4_fu_290_p2;
reg   [31:0] hashed_4_reg_2636;
wire   [25:0] add_ln12_3_fu_342_p2;
reg   [25:0] add_ln12_3_reg_2642;
reg   [0:0] ret_2_reg_2647;
wire   [14:0] add_ln10_2_fu_356_p2;
reg   [14:0] add_ln10_2_reg_2654;
reg   [0:0] ret_3_reg_2659;
reg   [0:0] ret_4_reg_2666;
reg   [0:0] ret_5_reg_2673;
reg   [0:0] ret_6_reg_2680;
reg   [0:0] ret_7_reg_2687;
reg   [0:0] ret_8_reg_2694;
reg   [0:0] ret_9_reg_2701;
reg   [0:0] ret_10_reg_2708;
reg   [0:0] ret_11_reg_2715;
reg   [0:0] ret_12_reg_2722;
reg   [0:0] ret_13_reg_2729;
reg   [0:0] ret_14_reg_2736;
reg   [0:0] ret_15_reg_2743;
reg   [0:0] ret_16_reg_2750;
reg   [0:0] ret_17_reg_2757;
reg   [0:0] ret_18_reg_2764;
reg   [0:0] tmp_22_reg_2771;
wire   [25:0] xor_ln10_2_fu_656_p2;
reg   [25:0] xor_ln10_2_reg_2778;
wire    ap_CS_fsm_state2;
wire   [31:0] hashed_10_fu_662_p2;
reg   [31:0] hashed_10_reg_2783;
wire   [14:0] xor_ln11_2_fu_668_p2;
reg   [14:0] xor_ln11_2_reg_2789;
wire   [15:0] trunc_ln11_21_fu_674_p1;
reg   [15:0] trunc_ln11_21_reg_2794;
wire   [4:0] trunc_ln12_6_fu_678_p1;
reg   [4:0] trunc_ln12_6_reg_2799;
wire   [25:0] xor_ln10_4_fu_884_p2;
reg   [25:0] xor_ln10_4_reg_2804;
wire    ap_CS_fsm_state3;
wire   [31:0] hashed_16_fu_890_p2;
reg   [31:0] hashed_16_reg_2809;
wire   [14:0] xor_ln11_4_fu_896_p2;
reg   [14:0] xor_ln11_4_reg_2815;
wire   [15:0] trunc_ln11_23_fu_902_p1;
reg   [15:0] trunc_ln11_23_reg_2820;
wire   [4:0] trunc_ln12_11_fu_906_p1;
reg   [4:0] trunc_ln12_11_reg_2825;
wire   [25:0] xor_ln10_6_fu_1112_p2;
reg   [25:0] xor_ln10_6_reg_2830;
wire    ap_CS_fsm_state4;
wire   [31:0] hashed_22_fu_1118_p2;
reg   [31:0] hashed_22_reg_2835;
wire   [14:0] xor_ln11_6_fu_1124_p2;
reg   [14:0] xor_ln11_6_reg_2841;
wire   [15:0] trunc_ln11_25_fu_1130_p1;
reg   [15:0] trunc_ln11_25_reg_2846;
wire   [4:0] trunc_ln12_15_fu_1134_p1;
reg   [4:0] trunc_ln12_15_reg_2851;
wire   [25:0] xor_ln10_8_fu_1340_p2;
reg   [25:0] xor_ln10_8_reg_2856;
wire    ap_CS_fsm_state5;
wire   [31:0] hashed_28_fu_1346_p2;
reg   [31:0] hashed_28_reg_2861;
wire   [14:0] xor_ln11_8_fu_1352_p2;
reg   [14:0] xor_ln11_8_reg_2867;
wire   [15:0] trunc_ln11_27_fu_1358_p1;
reg   [15:0] trunc_ln11_27_reg_2872;
wire   [4:0] trunc_ln12_19_fu_1362_p1;
reg   [4:0] trunc_ln12_19_reg_2877;
wire   [25:0] xor_ln10_10_fu_1568_p2;
reg   [25:0] xor_ln10_10_reg_2882;
wire    ap_CS_fsm_state6;
wire   [31:0] hashed_34_fu_1574_p2;
reg   [31:0] hashed_34_reg_2887;
wire   [14:0] xor_ln11_10_fu_1580_p2;
reg   [14:0] xor_ln11_10_reg_2893;
wire   [15:0] trunc_ln11_29_fu_1586_p1;
reg   [15:0] trunc_ln11_29_reg_2898;
wire   [4:0] trunc_ln12_23_fu_1590_p1;
reg   [4:0] trunc_ln12_23_reg_2903;
wire   [25:0] xor_ln10_12_fu_1796_p2;
reg   [25:0] xor_ln10_12_reg_2908;
wire    ap_CS_fsm_state7;
wire   [31:0] hashed_40_fu_1802_p2;
reg   [31:0] hashed_40_reg_2913;
wire   [14:0] xor_ln11_12_fu_1808_p2;
reg   [14:0] xor_ln11_12_reg_2919;
wire   [15:0] trunc_ln11_31_fu_1814_p1;
reg   [15:0] trunc_ln11_31_reg_2924;
wire   [4:0] trunc_ln12_27_fu_1818_p1;
reg   [4:0] trunc_ln12_27_reg_2929;
wire   [25:0] xor_ln10_14_fu_2024_p2;
reg   [25:0] xor_ln10_14_reg_2934;
wire    ap_CS_fsm_state8;
wire   [31:0] hashed_46_fu_2030_p2;
reg   [31:0] hashed_46_reg_2939;
wire   [14:0] xor_ln11_14_fu_2036_p2;
reg   [14:0] xor_ln11_14_reg_2945;
wire   [15:0] trunc_ln11_33_fu_2042_p1;
reg   [15:0] trunc_ln11_33_reg_2950;
wire   [4:0] trunc_ln12_31_fu_2046_p1;
reg   [4:0] trunc_ln12_31_reg_2955;
wire   [25:0] xor_ln10_16_fu_2252_p2;
reg   [25:0] xor_ln10_16_reg_2960;
wire    ap_CS_fsm_state9;
wire   [31:0] hashed_52_fu_2258_p2;
reg   [31:0] hashed_52_reg_2965;
wire   [14:0] xor_ln11_16_fu_2264_p2;
reg   [14:0] xor_ln11_16_reg_2971;
wire   [15:0] trunc_ln11_35_fu_2270_p1;
reg   [15:0] trunc_ln11_35_reg_2976;
wire   [4:0] trunc_ln12_35_fu_2274_p1;
reg   [4:0] trunc_ln12_35_reg_2981;
wire   [25:0] xor_ln10_18_fu_2480_p2;
reg   [25:0] xor_ln10_18_reg_2986;
wire    ap_CS_fsm_state10;
wire   [31:0] hashed_58_fu_2486_p2;
reg   [31:0] hashed_58_reg_2991;
wire   [14:0] xor_ln11_18_fu_2492_p2;
reg   [14:0] xor_ln11_18_reg_2997;
wire   [15:0] trunc_ln11_37_fu_2498_p1;
reg   [15:0] trunc_ln11_37_reg_3002;
wire   [4:0] trunc_ln5_1_fu_2502_p1;
reg   [4:0] trunc_ln5_1_reg_3007;
wire   [0:0] trunc_ln1497_fu_86_p1;
wire   [5:0] tmp_fu_90_p3;
wire   [15:0] zext_ln12_fu_98_p1;
wire   [0:0] ret_fu_116_p3;
wire   [31:0] hashed_fu_102_p6;
wire   [31:0] zext_ln1348_fu_124_p1;
wire   [31:0] hashed_1_fu_146_p2;
wire   [10:0] tmp_5_fu_162_p6;
wire   [25:0] tmp_1_fu_132_p6;
wire   [25:0] zext_ln10_fu_128_p1;
wire   [15:0] trunc_ln11_fu_186_p1;
wire   [31:0] shl_ln11_fu_152_p2;
wire   [31:0] hashed_2_fu_198_p2;
wire   [25:0] lshr_ln_fu_204_p4;
wire   [11:0] zext_ln11_1_fu_176_p1;
wire   [11:0] zext_ln11_fu_158_p1;
wire   [11:0] add_ln12_fu_218_p2;
wire   [4:0] trunc_ln12_fu_228_p1;
wire   [25:0] trunc_ln_fu_190_p3;
wire   [25:0] add_ln11_fu_180_p2;
wire   [31:0] zext_ln12_1_fu_214_p1;
wire   [0:0] ret_1_fu_252_p3;
wire   [14:0] trunc_ln12_1_fu_232_p3;
wire   [14:0] zext_ln12_20_fu_224_p1;
wire   [25:0] add_ln12_1_fu_240_p2;
wire   [31:0] hashed_3_fu_246_p2;
wire   [31:0] zext_ln1348_1_fu_260_p1;
wire   [14:0] trunc_ln1_fu_274_p4;
wire   [14:0] add_ln10_fu_268_p2;
wire   [25:0] xor_ln10_fu_284_p2;
wire   [25:0] zext_ln10_1_fu_264_p1;
wire   [15:0] trunc_ln11_19_fu_312_p1;
wire   [14:0] xor_ln11_fu_300_p2;
wire   [14:0] zext_ln11_2_fu_296_p1;
wire   [4:0] trunc_ln12_2_fu_330_p1;
wire   [25:0] trunc_ln11_1_fu_316_p3;
wire   [25:0] add_ln11_2_fu_306_p2;
wire   [14:0] trunc_ln12_3_fu_334_p3;
wire   [14:0] add_ln12_2_fu_324_p2;
wire   [31:0] shl_ln11_1_fu_498_p2;
wire   [31:0] hashed_5_fu_503_p2;
wire   [25:0] lshr_ln12_1_fu_508_p4;
wire   [31:0] zext_ln12_2_fu_518_p1;
wire   [31:0] hashed_6_fu_522_p2;
wire   [31:0] zext_ln1348_2_fu_528_p1;
wire   [31:0] hashed_7_fu_549_p2;
wire   [14:0] trunc_ln10_1_fu_534_p4;
wire   [25:0] xor_ln10_1_fu_544_p2;
wire   [25:0] zext_ln10_2_fu_531_p1;
wire   [15:0] trunc_ln11_20_fu_575_p1;
wire   [31:0] shl_ln11_2_fu_555_p2;
wire   [31:0] hashed_8_fu_587_p2;
wire   [25:0] lshr_ln12_2_fu_593_p4;
wire   [14:0] xor_ln11_1_fu_564_p2;
wire   [14:0] zext_ln11_3_fu_561_p1;
wire   [4:0] trunc_ln12_4_fu_613_p1;
wire   [25:0] trunc_ln11_2_fu_579_p3;
wire   [25:0] add_ln11_4_fu_569_p2;
wire   [31:0] zext_ln12_3_fu_603_p1;
wire   [14:0] trunc_ln12_5_fu_617_p3;
wire   [14:0] add_ln12_4_fu_607_p2;
wire   [25:0] add_ln12_5_fu_625_p2;
wire   [31:0] hashed_9_fu_631_p2;
wire   [31:0] zext_ln1348_3_fu_637_p1;
wire   [14:0] trunc_ln10_2_fu_646_p4;
wire   [14:0] add_ln10_4_fu_640_p2;
wire   [25:0] zext_ln10_3_fu_682_p1;
wire   [31:0] shl_ln11_3_fu_685_p2;
wire   [31:0] hashed_11_fu_705_p2;
wire   [25:0] lshr_ln12_3_fu_710_p4;
wire   [14:0] zext_ln11_4_fu_690_p1;
wire   [25:0] trunc_ln11_3_fu_698_p3;
wire   [25:0] add_ln11_6_fu_693_p2;
wire   [31:0] zext_ln12_4_fu_720_p1;
wire   [14:0] trunc_ln12_7_fu_729_p3;
wire   [14:0] add_ln12_6_fu_724_p2;
wire   [25:0] add_ln12_7_fu_736_p2;
wire   [31:0] hashed_12_fu_742_p2;
wire   [31:0] zext_ln1348_4_fu_748_p1;
wire   [31:0] hashed_13_fu_776_p2;
wire   [14:0] trunc_ln10_3_fu_760_p4;
wire   [14:0] add_ln10_6_fu_754_p2;
wire   [25:0] xor_ln10_3_fu_770_p2;
wire   [25:0] zext_ln10_4_fu_751_p1;
wire   [15:0] trunc_ln11_22_fu_803_p1;
wire   [31:0] shl_ln11_4_fu_782_p2;
wire   [31:0] hashed_14_fu_815_p2;
wire   [25:0] lshr_ln12_4_fu_821_p4;
wire   [14:0] xor_ln11_3_fu_791_p2;
wire   [14:0] zext_ln11_5_fu_788_p1;
wire   [4:0] trunc_ln12_8_fu_841_p1;
wire   [25:0] trunc_ln11_4_fu_807_p3;
wire   [25:0] add_ln11_8_fu_797_p2;
wire   [31:0] zext_ln12_5_fu_831_p1;
wire   [14:0] trunc_ln12_9_fu_845_p3;
wire   [14:0] add_ln12_8_fu_835_p2;
wire   [25:0] add_ln12_9_fu_853_p2;
wire   [31:0] hashed_15_fu_859_p2;
wire   [31:0] zext_ln1348_5_fu_865_p1;
wire   [14:0] trunc_ln10_4_fu_874_p4;
wire   [14:0] add_ln10_8_fu_868_p2;
wire   [25:0] zext_ln10_5_fu_910_p1;
wire   [31:0] shl_ln11_5_fu_913_p2;
wire   [31:0] hashed_17_fu_933_p2;
wire   [25:0] lshr_ln12_5_fu_938_p4;
wire   [14:0] zext_ln11_6_fu_918_p1;
wire   [25:0] trunc_ln11_5_fu_926_p3;
wire   [25:0] add_ln11_10_fu_921_p2;
wire   [31:0] zext_ln12_6_fu_948_p1;
wire   [14:0] trunc_ln12_s_fu_957_p3;
wire   [14:0] add_ln12_10_fu_952_p2;
wire   [25:0] add_ln12_11_fu_964_p2;
wire   [31:0] hashed_18_fu_970_p2;
wire   [31:0] zext_ln1348_6_fu_976_p1;
wire   [31:0] hashed_19_fu_1004_p2;
wire   [14:0] trunc_ln10_5_fu_988_p4;
wire   [14:0] add_ln10_10_fu_982_p2;
wire   [25:0] xor_ln10_5_fu_998_p2;
wire   [25:0] zext_ln10_6_fu_979_p1;
wire   [15:0] trunc_ln11_24_fu_1031_p1;
wire   [31:0] shl_ln11_6_fu_1010_p2;
wire   [31:0] hashed_20_fu_1043_p2;
wire   [25:0] lshr_ln12_6_fu_1049_p4;
wire   [14:0] xor_ln11_5_fu_1019_p2;
wire   [14:0] zext_ln11_7_fu_1016_p1;
wire   [4:0] trunc_ln12_13_fu_1069_p1;
wire   [25:0] trunc_ln11_6_fu_1035_p3;
wire   [25:0] add_ln11_12_fu_1025_p2;
wire   [31:0] zext_ln12_7_fu_1059_p1;
wire   [14:0] trunc_ln12_10_fu_1073_p3;
wire   [14:0] add_ln12_12_fu_1063_p2;
wire   [25:0] add_ln12_13_fu_1081_p2;
wire   [31:0] hashed_21_fu_1087_p2;
wire   [31:0] zext_ln1348_7_fu_1093_p1;
wire   [14:0] trunc_ln10_6_fu_1102_p4;
wire   [14:0] add_ln10_12_fu_1096_p2;
wire   [25:0] zext_ln10_7_fu_1138_p1;
wire   [31:0] shl_ln11_7_fu_1141_p2;
wire   [31:0] hashed_23_fu_1161_p2;
wire   [25:0] lshr_ln12_7_fu_1166_p4;
wire   [14:0] zext_ln11_8_fu_1146_p1;
wire   [25:0] trunc_ln11_7_fu_1154_p3;
wire   [25:0] add_ln11_14_fu_1149_p2;
wire   [31:0] zext_ln12_8_fu_1176_p1;
wire   [14:0] trunc_ln12_12_fu_1185_p3;
wire   [14:0] add_ln12_14_fu_1180_p2;
wire   [25:0] add_ln12_15_fu_1192_p2;
wire   [31:0] hashed_24_fu_1198_p2;
wire   [31:0] zext_ln1348_8_fu_1204_p1;
wire   [31:0] hashed_25_fu_1232_p2;
wire   [14:0] trunc_ln10_7_fu_1216_p4;
wire   [14:0] add_ln10_14_fu_1210_p2;
wire   [25:0] xor_ln10_7_fu_1226_p2;
wire   [25:0] zext_ln10_8_fu_1207_p1;
wire   [15:0] trunc_ln11_26_fu_1259_p1;
wire   [31:0] shl_ln11_8_fu_1238_p2;
wire   [31:0] hashed_26_fu_1271_p2;
wire   [25:0] lshr_ln12_8_fu_1277_p4;
wire   [14:0] xor_ln11_7_fu_1247_p2;
wire   [14:0] zext_ln11_9_fu_1244_p1;
wire   [4:0] trunc_ln12_17_fu_1297_p1;
wire   [25:0] trunc_ln11_8_fu_1263_p3;
wire   [25:0] add_ln11_16_fu_1253_p2;
wire   [31:0] zext_ln12_9_fu_1287_p1;
wire   [14:0] trunc_ln12_14_fu_1301_p3;
wire   [14:0] add_ln12_16_fu_1291_p2;
wire   [25:0] add_ln12_17_fu_1309_p2;
wire   [31:0] hashed_27_fu_1315_p2;
wire   [31:0] zext_ln1348_9_fu_1321_p1;
wire   [14:0] trunc_ln10_8_fu_1330_p4;
wire   [14:0] add_ln10_16_fu_1324_p2;
wire   [25:0] zext_ln10_9_fu_1366_p1;
wire   [31:0] shl_ln11_9_fu_1369_p2;
wire   [31:0] hashed_29_fu_1389_p2;
wire   [25:0] lshr_ln12_9_fu_1394_p4;
wire   [14:0] zext_ln11_10_fu_1374_p1;
wire   [25:0] trunc_ln11_9_fu_1382_p3;
wire   [25:0] add_ln11_18_fu_1377_p2;
wire   [31:0] zext_ln12_10_fu_1404_p1;
wire   [14:0] trunc_ln12_16_fu_1413_p3;
wire   [14:0] add_ln12_18_fu_1408_p2;
wire   [25:0] add_ln12_19_fu_1420_p2;
wire   [31:0] hashed_30_fu_1426_p2;
wire   [31:0] zext_ln1348_10_fu_1432_p1;
wire   [31:0] hashed_31_fu_1460_p2;
wire   [14:0] trunc_ln10_9_fu_1444_p4;
wire   [14:0] add_ln10_18_fu_1438_p2;
wire   [25:0] xor_ln10_9_fu_1454_p2;
wire   [25:0] zext_ln10_10_fu_1435_p1;
wire   [15:0] trunc_ln11_28_fu_1487_p1;
wire   [31:0] shl_ln11_10_fu_1466_p2;
wire   [31:0] hashed_32_fu_1499_p2;
wire   [25:0] lshr_ln12_s_fu_1505_p4;
wire   [14:0] xor_ln11_9_fu_1475_p2;
wire   [14:0] zext_ln11_11_fu_1472_p1;
wire   [4:0] trunc_ln12_21_fu_1525_p1;
wire   [25:0] trunc_ln11_s_fu_1491_p3;
wire   [25:0] add_ln11_20_fu_1481_p2;
wire   [31:0] zext_ln12_11_fu_1515_p1;
wire   [14:0] trunc_ln12_18_fu_1529_p3;
wire   [14:0] add_ln12_20_fu_1519_p2;
wire   [25:0] add_ln12_21_fu_1537_p2;
wire   [31:0] hashed_33_fu_1543_p2;
wire   [31:0] zext_ln1348_11_fu_1549_p1;
wire   [14:0] trunc_ln10_s_fu_1558_p4;
wire   [14:0] add_ln10_20_fu_1552_p2;
wire   [25:0] zext_ln10_11_fu_1594_p1;
wire   [31:0] shl_ln11_11_fu_1597_p2;
wire   [31:0] hashed_35_fu_1617_p2;
wire   [25:0] lshr_ln12_10_fu_1622_p4;
wire   [14:0] zext_ln11_12_fu_1602_p1;
wire   [25:0] trunc_ln11_10_fu_1610_p3;
wire   [25:0] add_ln11_22_fu_1605_p2;
wire   [31:0] zext_ln12_12_fu_1632_p1;
wire   [14:0] trunc_ln12_20_fu_1641_p3;
wire   [14:0] add_ln12_22_fu_1636_p2;
wire   [25:0] add_ln12_23_fu_1648_p2;
wire   [31:0] hashed_36_fu_1654_p2;
wire   [31:0] zext_ln1348_12_fu_1660_p1;
wire   [31:0] hashed_37_fu_1688_p2;
wire   [14:0] trunc_ln10_10_fu_1672_p4;
wire   [14:0] add_ln10_22_fu_1666_p2;
wire   [25:0] xor_ln10_11_fu_1682_p2;
wire   [25:0] zext_ln10_12_fu_1663_p1;
wire   [15:0] trunc_ln11_30_fu_1715_p1;
wire   [31:0] shl_ln11_12_fu_1694_p2;
wire   [31:0] hashed_38_fu_1727_p2;
wire   [25:0] lshr_ln12_11_fu_1733_p4;
wire   [14:0] xor_ln11_11_fu_1703_p2;
wire   [14:0] zext_ln11_13_fu_1700_p1;
wire   [4:0] trunc_ln12_25_fu_1753_p1;
wire   [25:0] trunc_ln11_11_fu_1719_p3;
wire   [25:0] add_ln11_24_fu_1709_p2;
wire   [31:0] zext_ln12_13_fu_1743_p1;
wire   [14:0] trunc_ln12_22_fu_1757_p3;
wire   [14:0] add_ln12_24_fu_1747_p2;
wire   [25:0] add_ln12_25_fu_1765_p2;
wire   [31:0] hashed_39_fu_1771_p2;
wire   [31:0] zext_ln1348_13_fu_1777_p1;
wire   [14:0] trunc_ln10_11_fu_1786_p4;
wire   [14:0] add_ln10_24_fu_1780_p2;
wire   [25:0] zext_ln10_13_fu_1822_p1;
wire   [31:0] shl_ln11_13_fu_1825_p2;
wire   [31:0] hashed_41_fu_1845_p2;
wire   [25:0] lshr_ln12_12_fu_1850_p4;
wire   [14:0] zext_ln11_14_fu_1830_p1;
wire   [25:0] trunc_ln11_12_fu_1838_p3;
wire   [25:0] add_ln11_26_fu_1833_p2;
wire   [31:0] zext_ln12_14_fu_1860_p1;
wire   [14:0] trunc_ln12_24_fu_1869_p3;
wire   [14:0] add_ln12_26_fu_1864_p2;
wire   [25:0] add_ln12_27_fu_1876_p2;
wire   [31:0] hashed_42_fu_1882_p2;
wire   [31:0] zext_ln1348_14_fu_1888_p1;
wire   [31:0] hashed_43_fu_1916_p2;
wire   [14:0] trunc_ln10_12_fu_1900_p4;
wire   [14:0] add_ln10_26_fu_1894_p2;
wire   [25:0] xor_ln10_13_fu_1910_p2;
wire   [25:0] zext_ln10_14_fu_1891_p1;
wire   [15:0] trunc_ln11_32_fu_1943_p1;
wire   [31:0] shl_ln11_14_fu_1922_p2;
wire   [31:0] hashed_44_fu_1955_p2;
wire   [25:0] lshr_ln12_13_fu_1961_p4;
wire   [14:0] xor_ln11_13_fu_1931_p2;
wire   [14:0] zext_ln11_15_fu_1928_p1;
wire   [4:0] trunc_ln12_29_fu_1981_p1;
wire   [25:0] trunc_ln11_13_fu_1947_p3;
wire   [25:0] add_ln11_28_fu_1937_p2;
wire   [31:0] zext_ln12_15_fu_1971_p1;
wire   [14:0] trunc_ln12_26_fu_1985_p3;
wire   [14:0] add_ln12_28_fu_1975_p2;
wire   [25:0] add_ln12_29_fu_1993_p2;
wire   [31:0] hashed_45_fu_1999_p2;
wire   [31:0] zext_ln1348_15_fu_2005_p1;
wire   [14:0] trunc_ln10_13_fu_2014_p4;
wire   [14:0] add_ln10_28_fu_2008_p2;
wire   [25:0] zext_ln10_15_fu_2050_p1;
wire   [31:0] shl_ln11_15_fu_2053_p2;
wire   [31:0] hashed_47_fu_2073_p2;
wire   [25:0] lshr_ln12_14_fu_2078_p4;
wire   [14:0] zext_ln11_16_fu_2058_p1;
wire   [25:0] trunc_ln11_14_fu_2066_p3;
wire   [25:0] add_ln11_30_fu_2061_p2;
wire   [31:0] zext_ln12_16_fu_2088_p1;
wire   [14:0] trunc_ln12_28_fu_2097_p3;
wire   [14:0] add_ln12_30_fu_2092_p2;
wire   [25:0] add_ln12_31_fu_2104_p2;
wire   [31:0] hashed_48_fu_2110_p2;
wire   [31:0] zext_ln1348_16_fu_2116_p1;
wire   [31:0] hashed_49_fu_2144_p2;
wire   [14:0] trunc_ln10_14_fu_2128_p4;
wire   [14:0] add_ln10_30_fu_2122_p2;
wire   [25:0] xor_ln10_15_fu_2138_p2;
wire   [25:0] zext_ln10_16_fu_2119_p1;
wire   [15:0] trunc_ln11_34_fu_2171_p1;
wire   [31:0] shl_ln11_16_fu_2150_p2;
wire   [31:0] hashed_50_fu_2183_p2;
wire   [25:0] lshr_ln12_15_fu_2189_p4;
wire   [14:0] xor_ln11_15_fu_2159_p2;
wire   [14:0] zext_ln11_17_fu_2156_p1;
wire   [4:0] trunc_ln12_33_fu_2209_p1;
wire   [25:0] trunc_ln11_15_fu_2175_p3;
wire   [25:0] add_ln11_32_fu_2165_p2;
wire   [31:0] zext_ln12_17_fu_2199_p1;
wire   [14:0] trunc_ln12_30_fu_2213_p3;
wire   [14:0] add_ln12_32_fu_2203_p2;
wire   [25:0] add_ln12_33_fu_2221_p2;
wire   [31:0] hashed_51_fu_2227_p2;
wire   [31:0] zext_ln1348_17_fu_2233_p1;
wire   [14:0] trunc_ln10_15_fu_2242_p4;
wire   [14:0] add_ln10_32_fu_2236_p2;
wire   [25:0] zext_ln10_17_fu_2278_p1;
wire   [31:0] shl_ln11_17_fu_2281_p2;
wire   [31:0] hashed_53_fu_2301_p2;
wire   [25:0] lshr_ln12_16_fu_2306_p4;
wire   [14:0] zext_ln11_18_fu_2286_p1;
wire   [25:0] trunc_ln11_16_fu_2294_p3;
wire   [25:0] add_ln11_34_fu_2289_p2;
wire   [31:0] zext_ln12_18_fu_2316_p1;
wire   [14:0] trunc_ln12_32_fu_2325_p3;
wire   [14:0] add_ln12_34_fu_2320_p2;
wire   [25:0] add_ln12_35_fu_2332_p2;
wire   [31:0] hashed_54_fu_2338_p2;
wire   [31:0] zext_ln1348_18_fu_2344_p1;
wire   [31:0] hashed_55_fu_2372_p2;
wire   [14:0] trunc_ln10_16_fu_2356_p4;
wire   [14:0] add_ln10_34_fu_2350_p2;
wire   [25:0] xor_ln10_17_fu_2366_p2;
wire   [25:0] zext_ln10_18_fu_2347_p1;
wire   [15:0] trunc_ln11_36_fu_2399_p1;
wire   [31:0] shl_ln11_18_fu_2378_p2;
wire   [31:0] hashed_56_fu_2411_p2;
wire   [25:0] lshr_ln12_17_fu_2417_p4;
wire   [14:0] xor_ln11_17_fu_2387_p2;
wire   [14:0] zext_ln11_19_fu_2384_p1;
wire   [4:0] trunc_ln12_37_fu_2437_p1;
wire   [25:0] trunc_ln11_17_fu_2403_p3;
wire   [25:0] add_ln11_36_fu_2393_p2;
wire   [31:0] zext_ln12_19_fu_2427_p1;
wire   [14:0] trunc_ln12_34_fu_2441_p3;
wire   [14:0] add_ln12_36_fu_2431_p2;
wire   [25:0] add_ln12_37_fu_2449_p2;
wire   [31:0] hashed_57_fu_2455_p2;
wire   [31:0] zext_ln1348_19_fu_2461_p1;
wire   [14:0] trunc_ln10_17_fu_2470_p4;
wire   [14:0] add_ln10_36_fu_2464_p2;
wire    ap_CS_fsm_state11;
wire   [25:0] zext_ln10_19_fu_2506_p1;
wire   [31:0] shl_ln11_19_fu_2509_p2;
wire   [14:0] zext_ln11_20_fu_2514_p1;
wire   [25:0] trunc_ln11_18_fu_2522_p3;
wire   [25:0] add_ln11_38_fu_2517_p2;
wire   [31:0] hashed_59_fu_2529_p2;
wire   [14:0] trunc_ln5_fu_2539_p3;
wire   [14:0] add_ln5_fu_2534_p2;
wire   [25:0] trunc_ln12_36_fu_2552_p4;
wire   [25:0] add_ln5_1_fu_2546_p2;
wire   [25:0] hashed_60_fu_2578_p2;
wire   [14:0] trunc_ln12_38_fu_2568_p4;
wire   [14:0] add_ln12_38_fu_2562_p2;
wire   [11:0] trunc_ln14_fu_2596_p1;
wire   [25:0] shl_ln14_fu_2584_p2;
wire   [14:0] trunc_ln2_fu_2600_p3;
wire   [14:0] xor_ln14_fu_2590_p2;
wire   [25:0] hashed_61_fu_2608_p2;
wire   [14:0] trunc_ln3_fu_2620_p4;
wire   [14:0] add_ln5_2_fu_2614_p2;
reg   [10:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln10_2_reg_2654 <= add_ln10_2_fu_356_p2;
        add_ln12_3_reg_2642 <= add_ln12_3_fu_342_p2;
        hashed_4_reg_2636 <= hashed_4_fu_290_p2;
        ret_10_reg_2708 <= key[32'd11];
        ret_11_reg_2715 <= key[32'd12];
        ret_12_reg_2722 <= key[32'd13];
        ret_13_reg_2729 <= key[32'd14];
        ret_14_reg_2736 <= key[32'd15];
        ret_15_reg_2743 <= key[32'd16];
        ret_16_reg_2750 <= key[32'd17];
        ret_17_reg_2757 <= key[32'd18];
        ret_18_reg_2764 <= key[32'd19];
        ret_2_reg_2647 <= key[32'd3];
        ret_3_reg_2659 <= key[32'd4];
        ret_4_reg_2666 <= key[32'd5];
        ret_5_reg_2673 <= key[32'd6];
        ret_6_reg_2680 <= key[32'd7];
        ret_7_reg_2687 <= key[32'd8];
        ret_8_reg_2694 <= key[32'd9];
        ret_9_reg_2701 <= key[32'd10];
        tmp_22_reg_2771 <= key[32'd20];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        hashed_10_reg_2783 <= hashed_10_fu_662_p2;
        trunc_ln11_21_reg_2794 <= trunc_ln11_21_fu_674_p1;
        trunc_ln12_6_reg_2799 <= trunc_ln12_6_fu_678_p1;
        xor_ln10_2_reg_2778 <= xor_ln10_2_fu_656_p2;
        xor_ln11_2_reg_2789 <= xor_ln11_2_fu_668_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        hashed_16_reg_2809 <= hashed_16_fu_890_p2;
        trunc_ln11_23_reg_2820 <= trunc_ln11_23_fu_902_p1;
        trunc_ln12_11_reg_2825 <= trunc_ln12_11_fu_906_p1;
        xor_ln10_4_reg_2804 <= xor_ln10_4_fu_884_p2;
        xor_ln11_4_reg_2815 <= xor_ln11_4_fu_896_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hashed_22_reg_2835 <= hashed_22_fu_1118_p2;
        trunc_ln11_25_reg_2846 <= trunc_ln11_25_fu_1130_p1;
        trunc_ln12_15_reg_2851 <= trunc_ln12_15_fu_1134_p1;
        xor_ln10_6_reg_2830 <= xor_ln10_6_fu_1112_p2;
        xor_ln11_6_reg_2841 <= xor_ln11_6_fu_1124_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hashed_28_reg_2861 <= hashed_28_fu_1346_p2;
        trunc_ln11_27_reg_2872 <= trunc_ln11_27_fu_1358_p1;
        trunc_ln12_19_reg_2877 <= trunc_ln12_19_fu_1362_p1;
        xor_ln10_8_reg_2856 <= xor_ln10_8_fu_1340_p2;
        xor_ln11_8_reg_2867 <= xor_ln11_8_fu_1352_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        hashed_34_reg_2887 <= hashed_34_fu_1574_p2;
        trunc_ln11_29_reg_2898 <= trunc_ln11_29_fu_1586_p1;
        trunc_ln12_23_reg_2903 <= trunc_ln12_23_fu_1590_p1;
        xor_ln10_10_reg_2882 <= xor_ln10_10_fu_1568_p2;
        xor_ln11_10_reg_2893 <= xor_ln11_10_fu_1580_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        hashed_40_reg_2913 <= hashed_40_fu_1802_p2;
        trunc_ln11_31_reg_2924 <= trunc_ln11_31_fu_1814_p1;
        trunc_ln12_27_reg_2929 <= trunc_ln12_27_fu_1818_p1;
        xor_ln10_12_reg_2908 <= xor_ln10_12_fu_1796_p2;
        xor_ln11_12_reg_2919 <= xor_ln11_12_fu_1808_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hashed_46_reg_2939 <= hashed_46_fu_2030_p2;
        trunc_ln11_33_reg_2950 <= trunc_ln11_33_fu_2042_p1;
        trunc_ln12_31_reg_2955 <= trunc_ln12_31_fu_2046_p1;
        xor_ln10_14_reg_2934 <= xor_ln10_14_fu_2024_p2;
        xor_ln11_14_reg_2945 <= xor_ln11_14_fu_2036_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        hashed_52_reg_2965 <= hashed_52_fu_2258_p2;
        trunc_ln11_35_reg_2976 <= trunc_ln11_35_fu_2270_p1;
        trunc_ln12_35_reg_2981 <= trunc_ln12_35_fu_2274_p1;
        xor_ln10_16_reg_2960 <= xor_ln10_16_fu_2252_p2;
        xor_ln11_16_reg_2971 <= xor_ln11_16_fu_2264_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hashed_58_reg_2991 <= hashed_58_fu_2486_p2;
        trunc_ln11_37_reg_3002 <= trunc_ln11_37_fu_2498_p1;
        trunc_ln5_1_reg_3007 <= trunc_ln5_1_fu_2502_p1;
        xor_ln10_18_reg_2986 <= xor_ln10_18_fu_2480_p2;
        xor_ln11_18_reg_2997 <= xor_ln11_18_fu_2492_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_10_fu_982_p2 = (trunc_ln12_s_fu_957_p3 + add_ln12_10_fu_952_p2);

assign add_ln10_12_fu_1096_p2 = (trunc_ln12_10_fu_1073_p3 + add_ln12_12_fu_1063_p2);

assign add_ln10_14_fu_1210_p2 = (trunc_ln12_12_fu_1185_p3 + add_ln12_14_fu_1180_p2);

assign add_ln10_16_fu_1324_p2 = (trunc_ln12_14_fu_1301_p3 + add_ln12_16_fu_1291_p2);

assign add_ln10_18_fu_1438_p2 = (trunc_ln12_16_fu_1413_p3 + add_ln12_18_fu_1408_p2);

assign add_ln10_20_fu_1552_p2 = (trunc_ln12_18_fu_1529_p3 + add_ln12_20_fu_1519_p2);

assign add_ln10_22_fu_1666_p2 = (trunc_ln12_20_fu_1641_p3 + add_ln12_22_fu_1636_p2);

assign add_ln10_24_fu_1780_p2 = (trunc_ln12_22_fu_1757_p3 + add_ln12_24_fu_1747_p2);

assign add_ln10_26_fu_1894_p2 = (trunc_ln12_24_fu_1869_p3 + add_ln12_26_fu_1864_p2);

assign add_ln10_28_fu_2008_p2 = (trunc_ln12_26_fu_1985_p3 + add_ln12_28_fu_1975_p2);

assign add_ln10_2_fu_356_p2 = (trunc_ln12_3_fu_334_p3 + add_ln12_2_fu_324_p2);

assign add_ln10_30_fu_2122_p2 = (trunc_ln12_28_fu_2097_p3 + add_ln12_30_fu_2092_p2);

assign add_ln10_32_fu_2236_p2 = (trunc_ln12_30_fu_2213_p3 + add_ln12_32_fu_2203_p2);

assign add_ln10_34_fu_2350_p2 = (trunc_ln12_32_fu_2325_p3 + add_ln12_34_fu_2320_p2);

assign add_ln10_36_fu_2464_p2 = (trunc_ln12_34_fu_2441_p3 + add_ln12_36_fu_2431_p2);

assign add_ln10_4_fu_640_p2 = (trunc_ln12_5_fu_617_p3 + add_ln12_4_fu_607_p2);

assign add_ln10_6_fu_754_p2 = (trunc_ln12_7_fu_729_p3 + add_ln12_6_fu_724_p2);

assign add_ln10_8_fu_868_p2 = (trunc_ln12_9_fu_845_p3 + add_ln12_8_fu_835_p2);

assign add_ln10_fu_268_p2 = (trunc_ln12_1_fu_232_p3 + zext_ln12_20_fu_224_p1);

assign add_ln11_10_fu_921_p2 = (xor_ln10_4_reg_2804 + zext_ln10_5_fu_910_p1);

assign add_ln11_12_fu_1025_p2 = (xor_ln10_5_fu_998_p2 + zext_ln10_6_fu_979_p1);

assign add_ln11_14_fu_1149_p2 = (xor_ln10_6_reg_2830 + zext_ln10_7_fu_1138_p1);

assign add_ln11_16_fu_1253_p2 = (xor_ln10_7_fu_1226_p2 + zext_ln10_8_fu_1207_p1);

assign add_ln11_18_fu_1377_p2 = (xor_ln10_8_reg_2856 + zext_ln10_9_fu_1366_p1);

assign add_ln11_20_fu_1481_p2 = (xor_ln10_9_fu_1454_p2 + zext_ln10_10_fu_1435_p1);

assign add_ln11_22_fu_1605_p2 = (xor_ln10_10_reg_2882 + zext_ln10_11_fu_1594_p1);

assign add_ln11_24_fu_1709_p2 = (xor_ln10_11_fu_1682_p2 + zext_ln10_12_fu_1663_p1);

assign add_ln11_26_fu_1833_p2 = (xor_ln10_12_reg_2908 + zext_ln10_13_fu_1822_p1);

assign add_ln11_28_fu_1937_p2 = (xor_ln10_13_fu_1910_p2 + zext_ln10_14_fu_1891_p1);

assign add_ln11_2_fu_306_p2 = (xor_ln10_fu_284_p2 + zext_ln10_1_fu_264_p1);

assign add_ln11_30_fu_2061_p2 = (xor_ln10_14_reg_2934 + zext_ln10_15_fu_2050_p1);

assign add_ln11_32_fu_2165_p2 = (xor_ln10_15_fu_2138_p2 + zext_ln10_16_fu_2119_p1);

assign add_ln11_34_fu_2289_p2 = (xor_ln10_16_reg_2960 + zext_ln10_17_fu_2278_p1);

assign add_ln11_36_fu_2393_p2 = (xor_ln10_17_fu_2366_p2 + zext_ln10_18_fu_2347_p1);

assign add_ln11_38_fu_2517_p2 = (xor_ln10_18_reg_2986 + zext_ln10_19_fu_2506_p1);

assign add_ln11_4_fu_569_p2 = (xor_ln10_1_fu_544_p2 + zext_ln10_2_fu_531_p1);

assign add_ln11_6_fu_693_p2 = (xor_ln10_2_reg_2778 + zext_ln10_3_fu_682_p1);

assign add_ln11_8_fu_797_p2 = (xor_ln10_3_fu_770_p2 + zext_ln10_4_fu_751_p1);

assign add_ln11_fu_180_p2 = (tmp_1_fu_132_p6 + zext_ln10_fu_128_p1);

assign add_ln12_10_fu_952_p2 = (xor_ln11_4_reg_2815 + zext_ln11_6_fu_918_p1);

assign add_ln12_11_fu_964_p2 = (trunc_ln11_5_fu_926_p3 + add_ln11_10_fu_921_p2);

assign add_ln12_12_fu_1063_p2 = (xor_ln11_5_fu_1019_p2 + zext_ln11_7_fu_1016_p1);

assign add_ln12_13_fu_1081_p2 = (trunc_ln11_6_fu_1035_p3 + add_ln11_12_fu_1025_p2);

assign add_ln12_14_fu_1180_p2 = (xor_ln11_6_reg_2841 + zext_ln11_8_fu_1146_p1);

assign add_ln12_15_fu_1192_p2 = (trunc_ln11_7_fu_1154_p3 + add_ln11_14_fu_1149_p2);

assign add_ln12_16_fu_1291_p2 = (xor_ln11_7_fu_1247_p2 + zext_ln11_9_fu_1244_p1);

assign add_ln12_17_fu_1309_p2 = (trunc_ln11_8_fu_1263_p3 + add_ln11_16_fu_1253_p2);

assign add_ln12_18_fu_1408_p2 = (xor_ln11_8_reg_2867 + zext_ln11_10_fu_1374_p1);

assign add_ln12_19_fu_1420_p2 = (trunc_ln11_9_fu_1382_p3 + add_ln11_18_fu_1377_p2);

assign add_ln12_1_fu_240_p2 = (trunc_ln_fu_190_p3 + add_ln11_fu_180_p2);

assign add_ln12_20_fu_1519_p2 = (xor_ln11_9_fu_1475_p2 + zext_ln11_11_fu_1472_p1);

assign add_ln12_21_fu_1537_p2 = (trunc_ln11_s_fu_1491_p3 + add_ln11_20_fu_1481_p2);

assign add_ln12_22_fu_1636_p2 = (xor_ln11_10_reg_2893 + zext_ln11_12_fu_1602_p1);

assign add_ln12_23_fu_1648_p2 = (trunc_ln11_10_fu_1610_p3 + add_ln11_22_fu_1605_p2);

assign add_ln12_24_fu_1747_p2 = (xor_ln11_11_fu_1703_p2 + zext_ln11_13_fu_1700_p1);

assign add_ln12_25_fu_1765_p2 = (trunc_ln11_11_fu_1719_p3 + add_ln11_24_fu_1709_p2);

assign add_ln12_26_fu_1864_p2 = (xor_ln11_12_reg_2919 + zext_ln11_14_fu_1830_p1);

assign add_ln12_27_fu_1876_p2 = (trunc_ln11_12_fu_1838_p3 + add_ln11_26_fu_1833_p2);

assign add_ln12_28_fu_1975_p2 = (xor_ln11_13_fu_1931_p2 + zext_ln11_15_fu_1928_p1);

assign add_ln12_29_fu_1993_p2 = (trunc_ln11_13_fu_1947_p3 + add_ln11_28_fu_1937_p2);

assign add_ln12_2_fu_324_p2 = (xor_ln11_fu_300_p2 + zext_ln11_2_fu_296_p1);

assign add_ln12_30_fu_2092_p2 = (xor_ln11_14_reg_2945 + zext_ln11_16_fu_2058_p1);

assign add_ln12_31_fu_2104_p2 = (trunc_ln11_14_fu_2066_p3 + add_ln11_30_fu_2061_p2);

assign add_ln12_32_fu_2203_p2 = (xor_ln11_15_fu_2159_p2 + zext_ln11_17_fu_2156_p1);

assign add_ln12_33_fu_2221_p2 = (trunc_ln11_15_fu_2175_p3 + add_ln11_32_fu_2165_p2);

assign add_ln12_34_fu_2320_p2 = (xor_ln11_16_reg_2971 + zext_ln11_18_fu_2286_p1);

assign add_ln12_35_fu_2332_p2 = (trunc_ln11_16_fu_2294_p3 + add_ln11_34_fu_2289_p2);

assign add_ln12_36_fu_2431_p2 = (xor_ln11_17_fu_2387_p2 + zext_ln11_19_fu_2384_p1);

assign add_ln12_37_fu_2449_p2 = (trunc_ln11_17_fu_2403_p3 + add_ln11_36_fu_2393_p2);

assign add_ln12_38_fu_2562_p2 = (trunc_ln5_fu_2539_p3 + add_ln5_fu_2534_p2);

assign add_ln12_3_fu_342_p2 = (trunc_ln11_1_fu_316_p3 + add_ln11_2_fu_306_p2);

assign add_ln12_4_fu_607_p2 = (xor_ln11_1_fu_564_p2 + zext_ln11_3_fu_561_p1);

assign add_ln12_5_fu_625_p2 = (trunc_ln11_2_fu_579_p3 + add_ln11_4_fu_569_p2);

assign add_ln12_6_fu_724_p2 = (xor_ln11_2_reg_2789 + zext_ln11_4_fu_690_p1);

assign add_ln12_7_fu_736_p2 = (trunc_ln11_3_fu_698_p3 + add_ln11_6_fu_693_p2);

assign add_ln12_8_fu_835_p2 = (xor_ln11_3_fu_791_p2 + zext_ln11_5_fu_788_p1);

assign add_ln12_9_fu_853_p2 = (trunc_ln11_4_fu_807_p3 + add_ln11_8_fu_797_p2);

assign add_ln12_fu_218_p2 = (zext_ln11_1_fu_176_p1 + zext_ln11_fu_158_p1);

assign add_ln5_1_fu_2546_p2 = (trunc_ln11_18_fu_2522_p3 + add_ln11_38_fu_2517_p2);

assign add_ln5_2_fu_2614_p2 = (trunc_ln2_fu_2600_p3 + xor_ln14_fu_2590_p2);

assign add_ln5_fu_2534_p2 = (xor_ln11_18_reg_2997 + zext_ln11_20_fu_2514_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = (trunc_ln3_fu_2620_p4 ^ add_ln5_2_fu_2614_p2);

assign hashed_10_fu_662_p2 = (hashed_9_fu_631_p2 + zext_ln1348_3_fu_637_p1);

assign hashed_11_fu_705_p2 = (shl_ln11_3_fu_685_p2 + hashed_10_reg_2783);

assign hashed_12_fu_742_p2 = (zext_ln12_4_fu_720_p1 ^ hashed_11_fu_705_p2);

assign hashed_13_fu_776_p2 = (hashed_12_fu_742_p2 + zext_ln1348_4_fu_748_p1);

assign hashed_14_fu_815_p2 = (shl_ln11_4_fu_782_p2 + hashed_13_fu_776_p2);

assign hashed_15_fu_859_p2 = (zext_ln12_5_fu_831_p1 ^ hashed_14_fu_815_p2);

assign hashed_16_fu_890_p2 = (hashed_15_fu_859_p2 + zext_ln1348_5_fu_865_p1);

assign hashed_17_fu_933_p2 = (shl_ln11_5_fu_913_p2 + hashed_16_reg_2809);

assign hashed_18_fu_970_p2 = (zext_ln12_6_fu_948_p1 ^ hashed_17_fu_933_p2);

assign hashed_19_fu_1004_p2 = (hashed_18_fu_970_p2 + zext_ln1348_6_fu_976_p1);

assign hashed_1_fu_146_p2 = (hashed_fu_102_p6 + zext_ln1348_fu_124_p1);

assign hashed_20_fu_1043_p2 = (shl_ln11_6_fu_1010_p2 + hashed_19_fu_1004_p2);

assign hashed_21_fu_1087_p2 = (zext_ln12_7_fu_1059_p1 ^ hashed_20_fu_1043_p2);

assign hashed_22_fu_1118_p2 = (hashed_21_fu_1087_p2 + zext_ln1348_7_fu_1093_p1);

assign hashed_23_fu_1161_p2 = (shl_ln11_7_fu_1141_p2 + hashed_22_reg_2835);

assign hashed_24_fu_1198_p2 = (zext_ln12_8_fu_1176_p1 ^ hashed_23_fu_1161_p2);

assign hashed_25_fu_1232_p2 = (hashed_24_fu_1198_p2 + zext_ln1348_8_fu_1204_p1);

assign hashed_26_fu_1271_p2 = (shl_ln11_8_fu_1238_p2 + hashed_25_fu_1232_p2);

assign hashed_27_fu_1315_p2 = (zext_ln12_9_fu_1287_p1 ^ hashed_26_fu_1271_p2);

assign hashed_28_fu_1346_p2 = (hashed_27_fu_1315_p2 + zext_ln1348_9_fu_1321_p1);

assign hashed_29_fu_1389_p2 = (shl_ln11_9_fu_1369_p2 + hashed_28_reg_2861);

assign hashed_2_fu_198_p2 = (shl_ln11_fu_152_p2 + hashed_1_fu_146_p2);

assign hashed_30_fu_1426_p2 = (zext_ln12_10_fu_1404_p1 ^ hashed_29_fu_1389_p2);

assign hashed_31_fu_1460_p2 = (hashed_30_fu_1426_p2 + zext_ln1348_10_fu_1432_p1);

assign hashed_32_fu_1499_p2 = (shl_ln11_10_fu_1466_p2 + hashed_31_fu_1460_p2);

assign hashed_33_fu_1543_p2 = (zext_ln12_11_fu_1515_p1 ^ hashed_32_fu_1499_p2);

assign hashed_34_fu_1574_p2 = (hashed_33_fu_1543_p2 + zext_ln1348_11_fu_1549_p1);

assign hashed_35_fu_1617_p2 = (shl_ln11_11_fu_1597_p2 + hashed_34_reg_2887);

assign hashed_36_fu_1654_p2 = (zext_ln12_12_fu_1632_p1 ^ hashed_35_fu_1617_p2);

assign hashed_37_fu_1688_p2 = (hashed_36_fu_1654_p2 + zext_ln1348_12_fu_1660_p1);

assign hashed_38_fu_1727_p2 = (shl_ln11_12_fu_1694_p2 + hashed_37_fu_1688_p2);

assign hashed_39_fu_1771_p2 = (zext_ln12_13_fu_1743_p1 ^ hashed_38_fu_1727_p2);

assign hashed_3_fu_246_p2 = (zext_ln12_1_fu_214_p1 ^ hashed_2_fu_198_p2);

assign hashed_40_fu_1802_p2 = (hashed_39_fu_1771_p2 + zext_ln1348_13_fu_1777_p1);

assign hashed_41_fu_1845_p2 = (shl_ln11_13_fu_1825_p2 + hashed_40_reg_2913);

assign hashed_42_fu_1882_p2 = (zext_ln12_14_fu_1860_p1 ^ hashed_41_fu_1845_p2);

assign hashed_43_fu_1916_p2 = (hashed_42_fu_1882_p2 + zext_ln1348_14_fu_1888_p1);

assign hashed_44_fu_1955_p2 = (shl_ln11_14_fu_1922_p2 + hashed_43_fu_1916_p2);

assign hashed_45_fu_1999_p2 = (zext_ln12_15_fu_1971_p1 ^ hashed_44_fu_1955_p2);

assign hashed_46_fu_2030_p2 = (hashed_45_fu_1999_p2 + zext_ln1348_15_fu_2005_p1);

assign hashed_47_fu_2073_p2 = (shl_ln11_15_fu_2053_p2 + hashed_46_reg_2939);

assign hashed_48_fu_2110_p2 = (zext_ln12_16_fu_2088_p1 ^ hashed_47_fu_2073_p2);

assign hashed_49_fu_2144_p2 = (hashed_48_fu_2110_p2 + zext_ln1348_16_fu_2116_p1);

assign hashed_4_fu_290_p2 = (hashed_3_fu_246_p2 + zext_ln1348_1_fu_260_p1);

assign hashed_50_fu_2183_p2 = (shl_ln11_16_fu_2150_p2 + hashed_49_fu_2144_p2);

assign hashed_51_fu_2227_p2 = (zext_ln12_17_fu_2199_p1 ^ hashed_50_fu_2183_p2);

assign hashed_52_fu_2258_p2 = (hashed_51_fu_2227_p2 + zext_ln1348_17_fu_2233_p1);

assign hashed_53_fu_2301_p2 = (shl_ln11_17_fu_2281_p2 + hashed_52_reg_2965);

assign hashed_54_fu_2338_p2 = (zext_ln12_18_fu_2316_p1 ^ hashed_53_fu_2301_p2);

assign hashed_55_fu_2372_p2 = (hashed_54_fu_2338_p2 + zext_ln1348_18_fu_2344_p1);

assign hashed_56_fu_2411_p2 = (shl_ln11_18_fu_2378_p2 + hashed_55_fu_2372_p2);

assign hashed_57_fu_2455_p2 = (zext_ln12_19_fu_2427_p1 ^ hashed_56_fu_2411_p2);

assign hashed_58_fu_2486_p2 = (hashed_57_fu_2455_p2 + zext_ln1348_19_fu_2461_p1);

assign hashed_59_fu_2529_p2 = (shl_ln11_19_fu_2509_p2 + hashed_58_reg_2991);

assign hashed_5_fu_503_p2 = (shl_ln11_1_fu_498_p2 + hashed_4_reg_2636);

assign hashed_60_fu_2578_p2 = (trunc_ln12_36_fu_2552_p4 ^ add_ln5_1_fu_2546_p2);

assign hashed_61_fu_2608_p2 = (shl_ln14_fu_2584_p2 + hashed_60_fu_2578_p2);

assign hashed_6_fu_522_p2 = (zext_ln12_2_fu_518_p1 ^ hashed_5_fu_503_p2);

assign hashed_7_fu_549_p2 = (hashed_6_fu_522_p2 + zext_ln1348_2_fu_528_p1);

assign hashed_8_fu_587_p2 = (shl_ln11_2_fu_555_p2 + hashed_7_fu_549_p2);

assign hashed_9_fu_631_p2 = (zext_ln12_3_fu_603_p1 ^ hashed_8_fu_587_p2);

assign hashed_fu_102_p6 = {{{{{{{{11'd0}, {zext_ln12_fu_98_p1}}}, {trunc_ln1497_fu_86_p1}}}, {3'd0}}}, {trunc_ln1497_fu_86_p1}};

assign lshr_ln12_10_fu_1622_p4 = {{hashed_35_fu_1617_p2[31:6]}};

assign lshr_ln12_11_fu_1733_p4 = {{hashed_38_fu_1727_p2[31:6]}};

assign lshr_ln12_12_fu_1850_p4 = {{hashed_41_fu_1845_p2[31:6]}};

assign lshr_ln12_13_fu_1961_p4 = {{hashed_44_fu_1955_p2[31:6]}};

assign lshr_ln12_14_fu_2078_p4 = {{hashed_47_fu_2073_p2[31:6]}};

assign lshr_ln12_15_fu_2189_p4 = {{hashed_50_fu_2183_p2[31:6]}};

assign lshr_ln12_16_fu_2306_p4 = {{hashed_53_fu_2301_p2[31:6]}};

assign lshr_ln12_17_fu_2417_p4 = {{hashed_56_fu_2411_p2[31:6]}};

assign lshr_ln12_1_fu_508_p4 = {{hashed_5_fu_503_p2[31:6]}};

assign lshr_ln12_2_fu_593_p4 = {{hashed_8_fu_587_p2[31:6]}};

assign lshr_ln12_3_fu_710_p4 = {{hashed_11_fu_705_p2[31:6]}};

assign lshr_ln12_4_fu_821_p4 = {{hashed_14_fu_815_p2[31:6]}};

assign lshr_ln12_5_fu_938_p4 = {{hashed_17_fu_933_p2[31:6]}};

assign lshr_ln12_6_fu_1049_p4 = {{hashed_20_fu_1043_p2[31:6]}};

assign lshr_ln12_7_fu_1166_p4 = {{hashed_23_fu_1161_p2[31:6]}};

assign lshr_ln12_8_fu_1277_p4 = {{hashed_26_fu_1271_p2[31:6]}};

assign lshr_ln12_9_fu_1394_p4 = {{hashed_29_fu_1389_p2[31:6]}};

assign lshr_ln12_s_fu_1505_p4 = {{hashed_32_fu_1499_p2[31:6]}};

assign lshr_ln_fu_204_p4 = {{hashed_2_fu_198_p2[31:6]}};

assign ret_1_fu_252_p3 = key[32'd2];

assign ret_fu_116_p3 = key[32'd1];

assign shl_ln11_10_fu_1466_p2 = hashed_31_fu_1460_p2 << 32'd10;

assign shl_ln11_11_fu_1597_p2 = hashed_34_reg_2887 << 32'd10;

assign shl_ln11_12_fu_1694_p2 = hashed_37_fu_1688_p2 << 32'd10;

assign shl_ln11_13_fu_1825_p2 = hashed_40_reg_2913 << 32'd10;

assign shl_ln11_14_fu_1922_p2 = hashed_43_fu_1916_p2 << 32'd10;

assign shl_ln11_15_fu_2053_p2 = hashed_46_reg_2939 << 32'd10;

assign shl_ln11_16_fu_2150_p2 = hashed_49_fu_2144_p2 << 32'd10;

assign shl_ln11_17_fu_2281_p2 = hashed_52_reg_2965 << 32'd10;

assign shl_ln11_18_fu_2378_p2 = hashed_55_fu_2372_p2 << 32'd10;

assign shl_ln11_19_fu_2509_p2 = hashed_58_reg_2991 << 32'd10;

assign shl_ln11_1_fu_498_p2 = hashed_4_reg_2636 << 32'd10;

assign shl_ln11_2_fu_555_p2 = hashed_7_fu_549_p2 << 32'd10;

assign shl_ln11_3_fu_685_p2 = hashed_10_reg_2783 << 32'd10;

assign shl_ln11_4_fu_782_p2 = hashed_13_fu_776_p2 << 32'd10;

assign shl_ln11_5_fu_913_p2 = hashed_16_reg_2809 << 32'd10;

assign shl_ln11_6_fu_1010_p2 = hashed_19_fu_1004_p2 << 32'd10;

assign shl_ln11_7_fu_1141_p2 = hashed_22_reg_2835 << 32'd10;

assign shl_ln11_8_fu_1238_p2 = hashed_25_fu_1232_p2 << 32'd10;

assign shl_ln11_9_fu_1369_p2 = hashed_28_reg_2861 << 32'd10;

assign shl_ln11_fu_152_p2 = hashed_1_fu_146_p2 << 32'd10;

assign shl_ln14_fu_2584_p2 = hashed_60_fu_2578_p2 << 26'd3;

assign tmp_1_fu_132_p6 = {{{{{{{{5'd0}, {zext_ln12_fu_98_p1}}}, {trunc_ln1497_fu_86_p1}}}, {3'd0}}}, {trunc_ln1497_fu_86_p1}};

assign tmp_5_fu_162_p6 = {{{{{trunc_ln1497_fu_86_p1}, {5'd0}}, {trunc_ln1497_fu_86_p1}}, {3'd0}}, {trunc_ln1497_fu_86_p1}};

assign tmp_fu_90_p3 = {{trunc_ln1497_fu_86_p1}, {5'd0}};

assign trunc_ln10_10_fu_1672_p4 = {{hashed_35_fu_1617_p2[20:6]}};

assign trunc_ln10_11_fu_1786_p4 = {{hashed_38_fu_1727_p2[20:6]}};

assign trunc_ln10_12_fu_1900_p4 = {{hashed_41_fu_1845_p2[20:6]}};

assign trunc_ln10_13_fu_2014_p4 = {{hashed_44_fu_1955_p2[20:6]}};

assign trunc_ln10_14_fu_2128_p4 = {{hashed_47_fu_2073_p2[20:6]}};

assign trunc_ln10_15_fu_2242_p4 = {{hashed_50_fu_2183_p2[20:6]}};

assign trunc_ln10_16_fu_2356_p4 = {{hashed_53_fu_2301_p2[20:6]}};

assign trunc_ln10_17_fu_2470_p4 = {{hashed_56_fu_2411_p2[20:6]}};

assign trunc_ln10_1_fu_534_p4 = {{hashed_5_fu_503_p2[20:6]}};

assign trunc_ln10_2_fu_646_p4 = {{hashed_8_fu_587_p2[20:6]}};

assign trunc_ln10_3_fu_760_p4 = {{hashed_11_fu_705_p2[20:6]}};

assign trunc_ln10_4_fu_874_p4 = {{hashed_14_fu_815_p2[20:6]}};

assign trunc_ln10_5_fu_988_p4 = {{hashed_17_fu_933_p2[20:6]}};

assign trunc_ln10_6_fu_1102_p4 = {{hashed_20_fu_1043_p2[20:6]}};

assign trunc_ln10_7_fu_1216_p4 = {{hashed_23_fu_1161_p2[20:6]}};

assign trunc_ln10_8_fu_1330_p4 = {{hashed_26_fu_1271_p2[20:6]}};

assign trunc_ln10_9_fu_1444_p4 = {{hashed_29_fu_1389_p2[20:6]}};

assign trunc_ln10_s_fu_1558_p4 = {{hashed_32_fu_1499_p2[20:6]}};

assign trunc_ln11_10_fu_1610_p3 = {{trunc_ln11_29_reg_2898}, {10'd0}};

assign trunc_ln11_11_fu_1719_p3 = {{trunc_ln11_30_fu_1715_p1}, {10'd0}};

assign trunc_ln11_12_fu_1838_p3 = {{trunc_ln11_31_reg_2924}, {10'd0}};

assign trunc_ln11_13_fu_1947_p3 = {{trunc_ln11_32_fu_1943_p1}, {10'd0}};

assign trunc_ln11_14_fu_2066_p3 = {{trunc_ln11_33_reg_2950}, {10'd0}};

assign trunc_ln11_15_fu_2175_p3 = {{trunc_ln11_34_fu_2171_p1}, {10'd0}};

assign trunc_ln11_16_fu_2294_p3 = {{trunc_ln11_35_reg_2976}, {10'd0}};

assign trunc_ln11_17_fu_2403_p3 = {{trunc_ln11_36_fu_2399_p1}, {10'd0}};

assign trunc_ln11_18_fu_2522_p3 = {{trunc_ln11_37_reg_3002}, {10'd0}};

assign trunc_ln11_19_fu_312_p1 = hashed_4_fu_290_p2[15:0];

assign trunc_ln11_1_fu_316_p3 = {{trunc_ln11_19_fu_312_p1}, {10'd0}};

assign trunc_ln11_20_fu_575_p1 = hashed_7_fu_549_p2[15:0];

assign trunc_ln11_21_fu_674_p1 = hashed_10_fu_662_p2[15:0];

assign trunc_ln11_22_fu_803_p1 = hashed_13_fu_776_p2[15:0];

assign trunc_ln11_23_fu_902_p1 = hashed_16_fu_890_p2[15:0];

assign trunc_ln11_24_fu_1031_p1 = hashed_19_fu_1004_p2[15:0];

assign trunc_ln11_25_fu_1130_p1 = hashed_22_fu_1118_p2[15:0];

assign trunc_ln11_26_fu_1259_p1 = hashed_25_fu_1232_p2[15:0];

assign trunc_ln11_27_fu_1358_p1 = hashed_28_fu_1346_p2[15:0];

assign trunc_ln11_28_fu_1487_p1 = hashed_31_fu_1460_p2[15:0];

assign trunc_ln11_29_fu_1586_p1 = hashed_34_fu_1574_p2[15:0];

assign trunc_ln11_2_fu_579_p3 = {{trunc_ln11_20_fu_575_p1}, {10'd0}};

assign trunc_ln11_30_fu_1715_p1 = hashed_37_fu_1688_p2[15:0];

assign trunc_ln11_31_fu_1814_p1 = hashed_40_fu_1802_p2[15:0];

assign trunc_ln11_32_fu_1943_p1 = hashed_43_fu_1916_p2[15:0];

assign trunc_ln11_33_fu_2042_p1 = hashed_46_fu_2030_p2[15:0];

assign trunc_ln11_34_fu_2171_p1 = hashed_49_fu_2144_p2[15:0];

assign trunc_ln11_35_fu_2270_p1 = hashed_52_fu_2258_p2[15:0];

assign trunc_ln11_36_fu_2399_p1 = hashed_55_fu_2372_p2[15:0];

assign trunc_ln11_37_fu_2498_p1 = hashed_58_fu_2486_p2[15:0];

assign trunc_ln11_3_fu_698_p3 = {{trunc_ln11_21_reg_2794}, {10'd0}};

assign trunc_ln11_4_fu_807_p3 = {{trunc_ln11_22_fu_803_p1}, {10'd0}};

assign trunc_ln11_5_fu_926_p3 = {{trunc_ln11_23_reg_2820}, {10'd0}};

assign trunc_ln11_6_fu_1035_p3 = {{trunc_ln11_24_fu_1031_p1}, {10'd0}};

assign trunc_ln11_7_fu_1154_p3 = {{trunc_ln11_25_reg_2846}, {10'd0}};

assign trunc_ln11_8_fu_1263_p3 = {{trunc_ln11_26_fu_1259_p1}, {10'd0}};

assign trunc_ln11_9_fu_1382_p3 = {{trunc_ln11_27_reg_2872}, {10'd0}};

assign trunc_ln11_fu_186_p1 = hashed_1_fu_146_p2[15:0];

assign trunc_ln11_s_fu_1491_p3 = {{trunc_ln11_28_fu_1487_p1}, {10'd0}};

assign trunc_ln12_10_fu_1073_p3 = {{trunc_ln12_13_fu_1069_p1}, {10'd0}};

assign trunc_ln12_11_fu_906_p1 = hashed_16_fu_890_p2[4:0];

assign trunc_ln12_12_fu_1185_p3 = {{trunc_ln12_15_reg_2851}, {10'd0}};

assign trunc_ln12_13_fu_1069_p1 = hashed_19_fu_1004_p2[4:0];

assign trunc_ln12_14_fu_1301_p3 = {{trunc_ln12_17_fu_1297_p1}, {10'd0}};

assign trunc_ln12_15_fu_1134_p1 = hashed_22_fu_1118_p2[4:0];

assign trunc_ln12_16_fu_1413_p3 = {{trunc_ln12_19_reg_2877}, {10'd0}};

assign trunc_ln12_17_fu_1297_p1 = hashed_25_fu_1232_p2[4:0];

assign trunc_ln12_18_fu_1529_p3 = {{trunc_ln12_21_fu_1525_p1}, {10'd0}};

assign trunc_ln12_19_fu_1362_p1 = hashed_28_fu_1346_p2[4:0];

assign trunc_ln12_1_fu_232_p3 = {{trunc_ln12_fu_228_p1}, {10'd0}};

assign trunc_ln12_20_fu_1641_p3 = {{trunc_ln12_23_reg_2903}, {10'd0}};

assign trunc_ln12_21_fu_1525_p1 = hashed_31_fu_1460_p2[4:0];

assign trunc_ln12_22_fu_1757_p3 = {{trunc_ln12_25_fu_1753_p1}, {10'd0}};

assign trunc_ln12_23_fu_1590_p1 = hashed_34_fu_1574_p2[4:0];

assign trunc_ln12_24_fu_1869_p3 = {{trunc_ln12_27_reg_2929}, {10'd0}};

assign trunc_ln12_25_fu_1753_p1 = hashed_37_fu_1688_p2[4:0];

assign trunc_ln12_26_fu_1985_p3 = {{trunc_ln12_29_fu_1981_p1}, {10'd0}};

assign trunc_ln12_27_fu_1818_p1 = hashed_40_fu_1802_p2[4:0];

assign trunc_ln12_28_fu_2097_p3 = {{trunc_ln12_31_reg_2955}, {10'd0}};

assign trunc_ln12_29_fu_1981_p1 = hashed_43_fu_1916_p2[4:0];

assign trunc_ln12_2_fu_330_p1 = hashed_4_fu_290_p2[4:0];

assign trunc_ln12_30_fu_2213_p3 = {{trunc_ln12_33_fu_2209_p1}, {10'd0}};

assign trunc_ln12_31_fu_2046_p1 = hashed_46_fu_2030_p2[4:0];

assign trunc_ln12_32_fu_2325_p3 = {{trunc_ln12_35_reg_2981}, {10'd0}};

assign trunc_ln12_33_fu_2209_p1 = hashed_49_fu_2144_p2[4:0];

assign trunc_ln12_34_fu_2441_p3 = {{trunc_ln12_37_fu_2437_p1}, {10'd0}};

assign trunc_ln12_35_fu_2274_p1 = hashed_52_fu_2258_p2[4:0];

assign trunc_ln12_36_fu_2552_p4 = {{hashed_59_fu_2529_p2[31:6]}};

assign trunc_ln12_37_fu_2437_p1 = hashed_55_fu_2372_p2[4:0];

assign trunc_ln12_38_fu_2568_p4 = {{hashed_59_fu_2529_p2[20:6]}};

assign trunc_ln12_3_fu_334_p3 = {{trunc_ln12_2_fu_330_p1}, {10'd0}};

assign trunc_ln12_4_fu_613_p1 = hashed_7_fu_549_p2[4:0];

assign trunc_ln12_5_fu_617_p3 = {{trunc_ln12_4_fu_613_p1}, {10'd0}};

assign trunc_ln12_6_fu_678_p1 = hashed_10_fu_662_p2[4:0];

assign trunc_ln12_7_fu_729_p3 = {{trunc_ln12_6_reg_2799}, {10'd0}};

assign trunc_ln12_8_fu_841_p1 = hashed_13_fu_776_p2[4:0];

assign trunc_ln12_9_fu_845_p3 = {{trunc_ln12_8_fu_841_p1}, {10'd0}};

assign trunc_ln12_fu_228_p1 = hashed_1_fu_146_p2[4:0];

assign trunc_ln12_s_fu_957_p3 = {{trunc_ln12_11_reg_2825}, {10'd0}};

assign trunc_ln1497_fu_86_p1 = key[0:0];

assign trunc_ln14_fu_2596_p1 = hashed_60_fu_2578_p2[11:0];

assign trunc_ln1_fu_274_p4 = {{hashed_2_fu_198_p2[20:6]}};

assign trunc_ln2_fu_2600_p3 = {{trunc_ln14_fu_2596_p1}, {3'd0}};

assign trunc_ln3_fu_2620_p4 = {{hashed_61_fu_2608_p2[25:11]}};

assign trunc_ln5_1_fu_2502_p1 = hashed_58_fu_2486_p2[4:0];

assign trunc_ln5_fu_2539_p3 = {{trunc_ln5_1_reg_3007}, {10'd0}};

assign trunc_ln_fu_190_p3 = {{trunc_ln11_fu_186_p1}, {10'd0}};

assign xor_ln10_10_fu_1568_p2 = (lshr_ln12_s_fu_1505_p4 ^ add_ln12_21_fu_1537_p2);

assign xor_ln10_11_fu_1682_p2 = (lshr_ln12_10_fu_1622_p4 ^ add_ln12_23_fu_1648_p2);

assign xor_ln10_12_fu_1796_p2 = (lshr_ln12_11_fu_1733_p4 ^ add_ln12_25_fu_1765_p2);

assign xor_ln10_13_fu_1910_p2 = (lshr_ln12_12_fu_1850_p4 ^ add_ln12_27_fu_1876_p2);

assign xor_ln10_14_fu_2024_p2 = (lshr_ln12_13_fu_1961_p4 ^ add_ln12_29_fu_1993_p2);

assign xor_ln10_15_fu_2138_p2 = (lshr_ln12_14_fu_2078_p4 ^ add_ln12_31_fu_2104_p2);

assign xor_ln10_16_fu_2252_p2 = (lshr_ln12_15_fu_2189_p4 ^ add_ln12_33_fu_2221_p2);

assign xor_ln10_17_fu_2366_p2 = (lshr_ln12_16_fu_2306_p4 ^ add_ln12_35_fu_2332_p2);

assign xor_ln10_18_fu_2480_p2 = (lshr_ln12_17_fu_2417_p4 ^ add_ln12_37_fu_2449_p2);

assign xor_ln10_1_fu_544_p2 = (lshr_ln12_1_fu_508_p4 ^ add_ln12_3_reg_2642);

assign xor_ln10_2_fu_656_p2 = (lshr_ln12_2_fu_593_p4 ^ add_ln12_5_fu_625_p2);

assign xor_ln10_3_fu_770_p2 = (lshr_ln12_3_fu_710_p4 ^ add_ln12_7_fu_736_p2);

assign xor_ln10_4_fu_884_p2 = (lshr_ln12_4_fu_821_p4 ^ add_ln12_9_fu_853_p2);

assign xor_ln10_5_fu_998_p2 = (lshr_ln12_5_fu_938_p4 ^ add_ln12_11_fu_964_p2);

assign xor_ln10_6_fu_1112_p2 = (lshr_ln12_6_fu_1049_p4 ^ add_ln12_13_fu_1081_p2);

assign xor_ln10_7_fu_1226_p2 = (lshr_ln12_7_fu_1166_p4 ^ add_ln12_15_fu_1192_p2);

assign xor_ln10_8_fu_1340_p2 = (lshr_ln12_8_fu_1277_p4 ^ add_ln12_17_fu_1309_p2);

assign xor_ln10_9_fu_1454_p2 = (lshr_ln12_9_fu_1394_p4 ^ add_ln12_19_fu_1420_p2);

assign xor_ln10_fu_284_p2 = (lshr_ln_fu_204_p4 ^ add_ln12_1_fu_240_p2);

assign xor_ln11_10_fu_1580_p2 = (trunc_ln10_s_fu_1558_p4 ^ add_ln10_20_fu_1552_p2);

assign xor_ln11_11_fu_1703_p2 = (trunc_ln10_10_fu_1672_p4 ^ add_ln10_22_fu_1666_p2);

assign xor_ln11_12_fu_1808_p2 = (trunc_ln10_11_fu_1786_p4 ^ add_ln10_24_fu_1780_p2);

assign xor_ln11_13_fu_1931_p2 = (trunc_ln10_12_fu_1900_p4 ^ add_ln10_26_fu_1894_p2);

assign xor_ln11_14_fu_2036_p2 = (trunc_ln10_13_fu_2014_p4 ^ add_ln10_28_fu_2008_p2);

assign xor_ln11_15_fu_2159_p2 = (trunc_ln10_14_fu_2128_p4 ^ add_ln10_30_fu_2122_p2);

assign xor_ln11_16_fu_2264_p2 = (trunc_ln10_15_fu_2242_p4 ^ add_ln10_32_fu_2236_p2);

assign xor_ln11_17_fu_2387_p2 = (trunc_ln10_16_fu_2356_p4 ^ add_ln10_34_fu_2350_p2);

assign xor_ln11_18_fu_2492_p2 = (trunc_ln10_17_fu_2470_p4 ^ add_ln10_36_fu_2464_p2);

assign xor_ln11_1_fu_564_p2 = (trunc_ln10_1_fu_534_p4 ^ add_ln10_2_reg_2654);

assign xor_ln11_2_fu_668_p2 = (trunc_ln10_2_fu_646_p4 ^ add_ln10_4_fu_640_p2);

assign xor_ln11_3_fu_791_p2 = (trunc_ln10_3_fu_760_p4 ^ add_ln10_6_fu_754_p2);

assign xor_ln11_4_fu_896_p2 = (trunc_ln10_4_fu_874_p4 ^ add_ln10_8_fu_868_p2);

assign xor_ln11_5_fu_1019_p2 = (trunc_ln10_5_fu_988_p4 ^ add_ln10_10_fu_982_p2);

assign xor_ln11_6_fu_1124_p2 = (trunc_ln10_6_fu_1102_p4 ^ add_ln10_12_fu_1096_p2);

assign xor_ln11_7_fu_1247_p2 = (trunc_ln10_7_fu_1216_p4 ^ add_ln10_14_fu_1210_p2);

assign xor_ln11_8_fu_1352_p2 = (trunc_ln10_8_fu_1330_p4 ^ add_ln10_16_fu_1324_p2);

assign xor_ln11_9_fu_1475_p2 = (trunc_ln10_9_fu_1444_p4 ^ add_ln10_18_fu_1438_p2);

assign xor_ln11_fu_300_p2 = (trunc_ln1_fu_274_p4 ^ add_ln10_fu_268_p2);

assign xor_ln14_fu_2590_p2 = (trunc_ln12_38_fu_2568_p4 ^ add_ln12_38_fu_2562_p2);

assign zext_ln10_10_fu_1435_p1 = ret_10_reg_2708;

assign zext_ln10_11_fu_1594_p1 = ret_11_reg_2715;

assign zext_ln10_12_fu_1663_p1 = ret_12_reg_2722;

assign zext_ln10_13_fu_1822_p1 = ret_13_reg_2729;

assign zext_ln10_14_fu_1891_p1 = ret_14_reg_2736;

assign zext_ln10_15_fu_2050_p1 = ret_15_reg_2743;

assign zext_ln10_16_fu_2119_p1 = ret_16_reg_2750;

assign zext_ln10_17_fu_2278_p1 = ret_17_reg_2757;

assign zext_ln10_18_fu_2347_p1 = ret_18_reg_2764;

assign zext_ln10_19_fu_2506_p1 = tmp_22_reg_2771;

assign zext_ln10_1_fu_264_p1 = ret_1_fu_252_p3;

assign zext_ln10_2_fu_531_p1 = ret_2_reg_2647;

assign zext_ln10_3_fu_682_p1 = ret_3_reg_2659;

assign zext_ln10_4_fu_751_p1 = ret_4_reg_2666;

assign zext_ln10_5_fu_910_p1 = ret_5_reg_2673;

assign zext_ln10_6_fu_979_p1 = ret_6_reg_2680;

assign zext_ln10_7_fu_1138_p1 = ret_7_reg_2687;

assign zext_ln10_8_fu_1207_p1 = ret_8_reg_2694;

assign zext_ln10_9_fu_1366_p1 = ret_9_reg_2701;

assign zext_ln10_fu_128_p1 = ret_fu_116_p3;

assign zext_ln11_10_fu_1374_p1 = ret_9_reg_2701;

assign zext_ln11_11_fu_1472_p1 = ret_10_reg_2708;

assign zext_ln11_12_fu_1602_p1 = ret_11_reg_2715;

assign zext_ln11_13_fu_1700_p1 = ret_12_reg_2722;

assign zext_ln11_14_fu_1830_p1 = ret_13_reg_2729;

assign zext_ln11_15_fu_1928_p1 = ret_14_reg_2736;

assign zext_ln11_16_fu_2058_p1 = ret_15_reg_2743;

assign zext_ln11_17_fu_2156_p1 = ret_16_reg_2750;

assign zext_ln11_18_fu_2286_p1 = ret_17_reg_2757;

assign zext_ln11_19_fu_2384_p1 = ret_18_reg_2764;

assign zext_ln11_1_fu_176_p1 = tmp_5_fu_162_p6;

assign zext_ln11_20_fu_2514_p1 = tmp_22_reg_2771;

assign zext_ln11_2_fu_296_p1 = ret_1_fu_252_p3;

assign zext_ln11_3_fu_561_p1 = ret_2_reg_2647;

assign zext_ln11_4_fu_690_p1 = ret_3_reg_2659;

assign zext_ln11_5_fu_788_p1 = ret_4_reg_2666;

assign zext_ln11_6_fu_918_p1 = ret_5_reg_2673;

assign zext_ln11_7_fu_1016_p1 = ret_6_reg_2680;

assign zext_ln11_8_fu_1146_p1 = ret_7_reg_2687;

assign zext_ln11_9_fu_1244_p1 = ret_8_reg_2694;

assign zext_ln11_fu_158_p1 = ret_fu_116_p3;

assign zext_ln12_10_fu_1404_p1 = lshr_ln12_9_fu_1394_p4;

assign zext_ln12_11_fu_1515_p1 = lshr_ln12_s_fu_1505_p4;

assign zext_ln12_12_fu_1632_p1 = lshr_ln12_10_fu_1622_p4;

assign zext_ln12_13_fu_1743_p1 = lshr_ln12_11_fu_1733_p4;

assign zext_ln12_14_fu_1860_p1 = lshr_ln12_12_fu_1850_p4;

assign zext_ln12_15_fu_1971_p1 = lshr_ln12_13_fu_1961_p4;

assign zext_ln12_16_fu_2088_p1 = lshr_ln12_14_fu_2078_p4;

assign zext_ln12_17_fu_2199_p1 = lshr_ln12_15_fu_2189_p4;

assign zext_ln12_18_fu_2316_p1 = lshr_ln12_16_fu_2306_p4;

assign zext_ln12_19_fu_2427_p1 = lshr_ln12_17_fu_2417_p4;

assign zext_ln12_1_fu_214_p1 = lshr_ln_fu_204_p4;

assign zext_ln12_20_fu_224_p1 = add_ln12_fu_218_p2;

assign zext_ln12_2_fu_518_p1 = lshr_ln12_1_fu_508_p4;

assign zext_ln12_3_fu_603_p1 = lshr_ln12_2_fu_593_p4;

assign zext_ln12_4_fu_720_p1 = lshr_ln12_3_fu_710_p4;

assign zext_ln12_5_fu_831_p1 = lshr_ln12_4_fu_821_p4;

assign zext_ln12_6_fu_948_p1 = lshr_ln12_5_fu_938_p4;

assign zext_ln12_7_fu_1059_p1 = lshr_ln12_6_fu_1049_p4;

assign zext_ln12_8_fu_1176_p1 = lshr_ln12_7_fu_1166_p4;

assign zext_ln12_9_fu_1287_p1 = lshr_ln12_8_fu_1277_p4;

assign zext_ln12_fu_98_p1 = tmp_fu_90_p3;

assign zext_ln1348_10_fu_1432_p1 = ret_10_reg_2708;

assign zext_ln1348_11_fu_1549_p1 = ret_11_reg_2715;

assign zext_ln1348_12_fu_1660_p1 = ret_12_reg_2722;

assign zext_ln1348_13_fu_1777_p1 = ret_13_reg_2729;

assign zext_ln1348_14_fu_1888_p1 = ret_14_reg_2736;

assign zext_ln1348_15_fu_2005_p1 = ret_15_reg_2743;

assign zext_ln1348_16_fu_2116_p1 = ret_16_reg_2750;

assign zext_ln1348_17_fu_2233_p1 = ret_17_reg_2757;

assign zext_ln1348_18_fu_2344_p1 = ret_18_reg_2764;

assign zext_ln1348_19_fu_2461_p1 = tmp_22_reg_2771;

assign zext_ln1348_1_fu_260_p1 = ret_1_fu_252_p3;

assign zext_ln1348_2_fu_528_p1 = ret_2_reg_2647;

assign zext_ln1348_3_fu_637_p1 = ret_3_reg_2659;

assign zext_ln1348_4_fu_748_p1 = ret_4_reg_2666;

assign zext_ln1348_5_fu_865_p1 = ret_5_reg_2673;

assign zext_ln1348_6_fu_976_p1 = ret_6_reg_2680;

assign zext_ln1348_7_fu_1093_p1 = ret_7_reg_2687;

assign zext_ln1348_8_fu_1204_p1 = ret_8_reg_2694;

assign zext_ln1348_9_fu_1321_p1 = ret_9_reg_2701;

assign zext_ln1348_fu_124_p1 = ret_fu_116_p3;

endmodule //LZW_hybrid_hash_HW_my_hash
