// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="krnl_LZW_krnl_LZW,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=6.667000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.866910,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=84,HLS_SYN_DSP=0,HLS_SYN_FF=5450,HLS_SYN_LUT=18967,HLS_VERSION=2020_2}" *)

module krnl_LZW (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_aximm0_AWVALID,
        m_axi_aximm0_AWREADY,
        m_axi_aximm0_AWADDR,
        m_axi_aximm0_AWID,
        m_axi_aximm0_AWLEN,
        m_axi_aximm0_AWSIZE,
        m_axi_aximm0_AWBURST,
        m_axi_aximm0_AWLOCK,
        m_axi_aximm0_AWCACHE,
        m_axi_aximm0_AWPROT,
        m_axi_aximm0_AWQOS,
        m_axi_aximm0_AWREGION,
        m_axi_aximm0_AWUSER,
        m_axi_aximm0_WVALID,
        m_axi_aximm0_WREADY,
        m_axi_aximm0_WDATA,
        m_axi_aximm0_WSTRB,
        m_axi_aximm0_WLAST,
        m_axi_aximm0_WID,
        m_axi_aximm0_WUSER,
        m_axi_aximm0_ARVALID,
        m_axi_aximm0_ARREADY,
        m_axi_aximm0_ARADDR,
        m_axi_aximm0_ARID,
        m_axi_aximm0_ARLEN,
        m_axi_aximm0_ARSIZE,
        m_axi_aximm0_ARBURST,
        m_axi_aximm0_ARLOCK,
        m_axi_aximm0_ARCACHE,
        m_axi_aximm0_ARPROT,
        m_axi_aximm0_ARQOS,
        m_axi_aximm0_ARREGION,
        m_axi_aximm0_ARUSER,
        m_axi_aximm0_RVALID,
        m_axi_aximm0_RREADY,
        m_axi_aximm0_RDATA,
        m_axi_aximm0_RLAST,
        m_axi_aximm0_RID,
        m_axi_aximm0_RUSER,
        m_axi_aximm0_RRESP,
        m_axi_aximm0_BVALID,
        m_axi_aximm0_BREADY,
        m_axi_aximm0_BRESP,
        m_axi_aximm0_BID,
        m_axi_aximm0_BUSER,
        m_axi_aximm1_AWVALID,
        m_axi_aximm1_AWREADY,
        m_axi_aximm1_AWADDR,
        m_axi_aximm1_AWID,
        m_axi_aximm1_AWLEN,
        m_axi_aximm1_AWSIZE,
        m_axi_aximm1_AWBURST,
        m_axi_aximm1_AWLOCK,
        m_axi_aximm1_AWCACHE,
        m_axi_aximm1_AWPROT,
        m_axi_aximm1_AWQOS,
        m_axi_aximm1_AWREGION,
        m_axi_aximm1_AWUSER,
        m_axi_aximm1_WVALID,
        m_axi_aximm1_WREADY,
        m_axi_aximm1_WDATA,
        m_axi_aximm1_WSTRB,
        m_axi_aximm1_WLAST,
        m_axi_aximm1_WID,
        m_axi_aximm1_WUSER,
        m_axi_aximm1_ARVALID,
        m_axi_aximm1_ARREADY,
        m_axi_aximm1_ARADDR,
        m_axi_aximm1_ARID,
        m_axi_aximm1_ARLEN,
        m_axi_aximm1_ARSIZE,
        m_axi_aximm1_ARBURST,
        m_axi_aximm1_ARLOCK,
        m_axi_aximm1_ARCACHE,
        m_axi_aximm1_ARPROT,
        m_axi_aximm1_ARQOS,
        m_axi_aximm1_ARREGION,
        m_axi_aximm1_ARUSER,
        m_axi_aximm1_RVALID,
        m_axi_aximm1_RREADY,
        m_axi_aximm1_RDATA,
        m_axi_aximm1_RLAST,
        m_axi_aximm1_RID,
        m_axi_aximm1_RUSER,
        m_axi_aximm1_RRESP,
        m_axi_aximm1_BVALID,
        m_axi_aximm1_BREADY,
        m_axi_aximm1_BRESP,
        m_axi_aximm1_BID,
        m_axi_aximm1_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_AXIMM0_ID_WIDTH = 1;
parameter    C_M_AXI_AXIMM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_AXIMM0_DATA_WIDTH = 32;
parameter    C_M_AXI_AXIMM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM0_USER_VALUE = 0;
parameter    C_M_AXI_AXIMM0_PROT_VALUE = 0;
parameter    C_M_AXI_AXIMM0_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 64;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_ID_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_AXIMM1_DATA_WIDTH = 32;
parameter    C_M_AXI_AXIMM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_USER_VALUE = 0;
parameter    C_M_AXI_AXIMM1_PROT_VALUE = 0;
parameter    C_M_AXI_AXIMM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_AXIMM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_AXIMM1_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_aximm0_AWVALID;
input   m_axi_aximm0_AWREADY;
output  [C_M_AXI_AXIMM0_ADDR_WIDTH - 1:0] m_axi_aximm0_AWADDR;
output  [C_M_AXI_AXIMM0_ID_WIDTH - 1:0] m_axi_aximm0_AWID;
output  [7:0] m_axi_aximm0_AWLEN;
output  [2:0] m_axi_aximm0_AWSIZE;
output  [1:0] m_axi_aximm0_AWBURST;
output  [1:0] m_axi_aximm0_AWLOCK;
output  [3:0] m_axi_aximm0_AWCACHE;
output  [2:0] m_axi_aximm0_AWPROT;
output  [3:0] m_axi_aximm0_AWQOS;
output  [3:0] m_axi_aximm0_AWREGION;
output  [C_M_AXI_AXIMM0_AWUSER_WIDTH - 1:0] m_axi_aximm0_AWUSER;
output   m_axi_aximm0_WVALID;
input   m_axi_aximm0_WREADY;
output  [C_M_AXI_AXIMM0_DATA_WIDTH - 1:0] m_axi_aximm0_WDATA;
output  [C_M_AXI_AXIMM0_WSTRB_WIDTH - 1:0] m_axi_aximm0_WSTRB;
output   m_axi_aximm0_WLAST;
output  [C_M_AXI_AXIMM0_ID_WIDTH - 1:0] m_axi_aximm0_WID;
output  [C_M_AXI_AXIMM0_WUSER_WIDTH - 1:0] m_axi_aximm0_WUSER;
output   m_axi_aximm0_ARVALID;
input   m_axi_aximm0_ARREADY;
output  [C_M_AXI_AXIMM0_ADDR_WIDTH - 1:0] m_axi_aximm0_ARADDR;
output  [C_M_AXI_AXIMM0_ID_WIDTH - 1:0] m_axi_aximm0_ARID;
output  [7:0] m_axi_aximm0_ARLEN;
output  [2:0] m_axi_aximm0_ARSIZE;
output  [1:0] m_axi_aximm0_ARBURST;
output  [1:0] m_axi_aximm0_ARLOCK;
output  [3:0] m_axi_aximm0_ARCACHE;
output  [2:0] m_axi_aximm0_ARPROT;
output  [3:0] m_axi_aximm0_ARQOS;
output  [3:0] m_axi_aximm0_ARREGION;
output  [C_M_AXI_AXIMM0_ARUSER_WIDTH - 1:0] m_axi_aximm0_ARUSER;
input   m_axi_aximm0_RVALID;
output   m_axi_aximm0_RREADY;
input  [C_M_AXI_AXIMM0_DATA_WIDTH - 1:0] m_axi_aximm0_RDATA;
input   m_axi_aximm0_RLAST;
input  [C_M_AXI_AXIMM0_ID_WIDTH - 1:0] m_axi_aximm0_RID;
input  [C_M_AXI_AXIMM0_RUSER_WIDTH - 1:0] m_axi_aximm0_RUSER;
input  [1:0] m_axi_aximm0_RRESP;
input   m_axi_aximm0_BVALID;
output   m_axi_aximm0_BREADY;
input  [1:0] m_axi_aximm0_BRESP;
input  [C_M_AXI_AXIMM0_ID_WIDTH - 1:0] m_axi_aximm0_BID;
input  [C_M_AXI_AXIMM0_BUSER_WIDTH - 1:0] m_axi_aximm0_BUSER;
output   m_axi_aximm1_AWVALID;
input   m_axi_aximm1_AWREADY;
output  [C_M_AXI_AXIMM1_ADDR_WIDTH - 1:0] m_axi_aximm1_AWADDR;
output  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_AWID;
output  [7:0] m_axi_aximm1_AWLEN;
output  [2:0] m_axi_aximm1_AWSIZE;
output  [1:0] m_axi_aximm1_AWBURST;
output  [1:0] m_axi_aximm1_AWLOCK;
output  [3:0] m_axi_aximm1_AWCACHE;
output  [2:0] m_axi_aximm1_AWPROT;
output  [3:0] m_axi_aximm1_AWQOS;
output  [3:0] m_axi_aximm1_AWREGION;
output  [C_M_AXI_AXIMM1_AWUSER_WIDTH - 1:0] m_axi_aximm1_AWUSER;
output   m_axi_aximm1_WVALID;
input   m_axi_aximm1_WREADY;
output  [C_M_AXI_AXIMM1_DATA_WIDTH - 1:0] m_axi_aximm1_WDATA;
output  [C_M_AXI_AXIMM1_WSTRB_WIDTH - 1:0] m_axi_aximm1_WSTRB;
output   m_axi_aximm1_WLAST;
output  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_WID;
output  [C_M_AXI_AXIMM1_WUSER_WIDTH - 1:0] m_axi_aximm1_WUSER;
output   m_axi_aximm1_ARVALID;
input   m_axi_aximm1_ARREADY;
output  [C_M_AXI_AXIMM1_ADDR_WIDTH - 1:0] m_axi_aximm1_ARADDR;
output  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_ARID;
output  [7:0] m_axi_aximm1_ARLEN;
output  [2:0] m_axi_aximm1_ARSIZE;
output  [1:0] m_axi_aximm1_ARBURST;
output  [1:0] m_axi_aximm1_ARLOCK;
output  [3:0] m_axi_aximm1_ARCACHE;
output  [2:0] m_axi_aximm1_ARPROT;
output  [3:0] m_axi_aximm1_ARQOS;
output  [3:0] m_axi_aximm1_ARREGION;
output  [C_M_AXI_AXIMM1_ARUSER_WIDTH - 1:0] m_axi_aximm1_ARUSER;
input   m_axi_aximm1_RVALID;
output   m_axi_aximm1_RREADY;
input  [C_M_AXI_AXIMM1_DATA_WIDTH - 1:0] m_axi_aximm1_RDATA;
input   m_axi_aximm1_RLAST;
input  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_RID;
input  [C_M_AXI_AXIMM1_RUSER_WIDTH - 1:0] m_axi_aximm1_RUSER;
input  [1:0] m_axi_aximm1_RRESP;
input   m_axi_aximm1_BVALID;
output   m_axi_aximm1_BREADY;
input  [1:0] m_axi_aximm1_BRESP;
input  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_BID;
input  [C_M_AXI_AXIMM1_BUSER_WIDTH - 1:0] m_axi_aximm1_BUSER;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire   [63:0] in_r;
wire   [63:0] input_length;
wire   [63:0] send_data;
wire   [63:0] output_length;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_continue;
wire    ap_idle;
wire    aximm0_AWREADY;
wire    aximm0_WREADY;
wire    aximm0_ARREADY;
wire    aximm0_RVALID;
wire   [15:0] aximm0_RDATA;
wire    aximm0_RLAST;
wire   [0:0] aximm0_RID;
wire   [0:0] aximm0_RUSER;
wire   [1:0] aximm0_RRESP;
wire    aximm0_BVALID;
wire   [1:0] aximm0_BRESP;
wire   [0:0] aximm0_BID;
wire   [0:0] aximm0_BUSER;
wire    aximm1_AWREADY;
wire    aximm1_WREADY;
wire    aximm1_ARREADY;
wire    aximm1_RVALID;
wire   [15:0] aximm1_RDATA;
wire    aximm1_RLAST;
wire   [0:0] aximm1_RID;
wire   [0:0] aximm1_RUSER;
wire   [1:0] aximm1_RRESP;
wire    aximm1_BVALID;
wire   [1:0] aximm1_BRESP;
wire   [0:0] aximm1_BID;
wire   [0:0] aximm1_BUSER;
wire   [15:0] store_array_i_q0;
wire   [15:0] store_array_i_q1;
wire   [15:0] input_length_temp_i_q0;
wire   [15:0] input_length_temp_t_q0;
wire    krnl_LZW_entry4_U0_ap_start;
wire    krnl_LZW_entry4_U0_ap_done;
wire    krnl_LZW_entry4_U0_ap_continue;
wire    krnl_LZW_entry4_U0_ap_idle;
wire    krnl_LZW_entry4_U0_ap_ready;
wire    krnl_LZW_entry4_U0_start_out;
wire    krnl_LZW_entry4_U0_start_write;
wire   [63:0] krnl_LZW_entry4_U0_in_out_din;
wire    krnl_LZW_entry4_U0_in_out_write;
wire   [63:0] krnl_LZW_entry4_U0_input_length_out_din;
wire    krnl_LZW_entry4_U0_input_length_out_write;
wire   [63:0] krnl_LZW_entry4_U0_send_data_out_din;
wire    krnl_LZW_entry4_U0_send_data_out_write;
wire   [63:0] krnl_LZW_entry4_U0_send_data_out1_din;
wire    krnl_LZW_entry4_U0_send_data_out1_write;
wire   [63:0] krnl_LZW_entry4_U0_output_length_out_din;
wire    krnl_LZW_entry4_U0_output_length_out_write;
wire    Loop_VITIS_LOOP_318_1_proc_U0_ap_start;
wire    Loop_VITIS_LOOP_318_1_proc_U0_ap_done;
wire    Loop_VITIS_LOOP_318_1_proc_U0_ap_continue;
wire    Loop_VITIS_LOOP_318_1_proc_U0_ap_idle;
wire    Loop_VITIS_LOOP_318_1_proc_U0_ap_ready;
wire   [1:0] Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_address0;
wire    Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_ce0;
wire    Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_we0;
wire   [15:0] Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_d0;
wire    Loop_VITIS_LOOP_318_1_proc_U0_input_length_read;
wire    Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWVALID;
wire   [63:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWADDR;
wire   [0:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWID;
wire   [31:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWLEN;
wire   [2:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWSIZE;
wire   [1:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWBURST;
wire   [1:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWLOCK;
wire   [3:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWCACHE;
wire   [2:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWPROT;
wire   [3:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWQOS;
wire   [3:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWREGION;
wire   [0:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWUSER;
wire    Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_WVALID;
wire   [15:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_WDATA;
wire   [1:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_WSTRB;
wire    Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_WLAST;
wire   [0:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_WID;
wire   [0:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_WUSER;
wire    Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARVALID;
wire   [63:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARADDR;
wire   [0:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARID;
wire   [31:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARLEN;
wire   [2:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARSIZE;
wire   [1:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARBURST;
wire   [1:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARLOCK;
wire   [3:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARCACHE;
wire   [2:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARPROT;
wire   [3:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARQOS;
wire   [3:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARREGION;
wire   [0:0] Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARUSER;
wire    Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_RREADY;
wire    Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_BREADY;
wire   [7:0] Loop_VITIS_LOOP_318_1_proc_U0_ap_return;
wire    ap_channel_done_num_chunks_loc_channel;
wire    num_chunks_loc_channel_full_n;
reg    ap_sync_reg_channel_write_num_chunks_loc_channel;
wire    ap_sync_channel_write_num_chunks_loc_channel;
wire    ap_channel_done_input_length_temp;
wire    Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_full_n;
reg    ap_sync_reg_channel_write_input_length_temp;
wire    ap_sync_channel_write_input_length_temp;
wire    Block_krnl_LZW_exit1_proc_U0_ap_start;
wire    Block_krnl_LZW_exit1_proc_U0_ap_done;
wire    Block_krnl_LZW_exit1_proc_U0_ap_continue;
wire    Block_krnl_LZW_exit1_proc_U0_ap_idle;
wire    Block_krnl_LZW_exit1_proc_U0_ap_ready;
wire    Block_krnl_LZW_exit1_proc_U0_send_data_read;
wire   [0:0] Block_krnl_LZW_exit1_proc_U0_ap_return_0;
wire   [63:0] Block_krnl_LZW_exit1_proc_U0_ap_return_1;
wire    ap_channel_done_p_loc_channel;
wire    p_loc_channel_full_n;
reg    ap_sync_reg_channel_write_p_loc_channel;
wire    ap_sync_channel_write_p_loc_channel;
wire    ap_channel_done_send_data_cast_loc_channel;
wire    send_data_cast_loc_channel_full_n;
reg    ap_sync_reg_channel_write_send_data_cast_loc_channel;
wire    ap_sync_channel_write_send_data_cast_loc_channel;
wire    Loop_VITIS_LOOP_325_2_proc_U0_ap_start;
wire    Loop_VITIS_LOOP_325_2_proc_U0_ap_done;
wire    Loop_VITIS_LOOP_325_2_proc_U0_ap_continue;
wire    Loop_VITIS_LOOP_325_2_proc_U0_ap_idle;
wire    Loop_VITIS_LOOP_325_2_proc_U0_ap_ready;
wire    Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWVALID;
wire   [63:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWADDR;
wire   [0:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWID;
wire   [31:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWLEN;
wire   [2:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWSIZE;
wire   [1:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWBURST;
wire   [1:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWLOCK;
wire   [3:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWCACHE;
wire   [2:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWPROT;
wire   [3:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWQOS;
wire   [3:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWREGION;
wire   [0:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWUSER;
wire    Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WVALID;
wire   [15:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WDATA;
wire   [1:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WSTRB;
wire    Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WLAST;
wire   [0:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WID;
wire   [0:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WUSER;
wire    Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARVALID;
wire   [63:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARADDR;
wire   [0:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARID;
wire   [31:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARLEN;
wire   [2:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARSIZE;
wire   [1:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARBURST;
wire   [1:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARLOCK;
wire   [3:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARCACHE;
wire   [2:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARPROT;
wire   [3:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARQOS;
wire   [3:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARREGION;
wire   [0:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARUSER;
wire    Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_RREADY;
wire    Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_BREADY;
wire   [11:0] Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_address0;
wire    Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_ce0;
wire    Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_we0;
wire   [15:0] Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_d0;
wire   [11:0] Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_address1;
wire    Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_ce1;
wire    Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_we1;
wire   [15:0] Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_d1;
wire    Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWVALID;
wire   [63:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWADDR;
wire   [0:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWID;
wire   [31:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWLEN;
wire   [2:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWSIZE;
wire   [1:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWBURST;
wire   [1:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWLOCK;
wire   [3:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWCACHE;
wire   [2:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWPROT;
wire   [3:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWQOS;
wire   [3:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWREGION;
wire   [0:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWUSER;
wire    Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WVALID;
wire   [15:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WDATA;
wire   [1:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WSTRB;
wire    Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WLAST;
wire   [0:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WID;
wire   [0:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WUSER;
wire    Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARVALID;
wire   [63:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARADDR;
wire   [0:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARID;
wire   [31:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARLEN;
wire   [2:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARSIZE;
wire   [1:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARBURST;
wire   [1:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARLOCK;
wire   [3:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARCACHE;
wire   [2:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARPROT;
wire   [3:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARQOS;
wire   [3:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARREGION;
wire   [0:0] Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARUSER;
wire    Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_RREADY;
wire    Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_BREADY;
wire    Loop_VITIS_LOOP_325_2_proc_U0_output_length_read;
wire   [1:0] Loop_VITIS_LOOP_325_2_proc_U0_input_length_temp_address0;
wire    Loop_VITIS_LOOP_325_2_proc_U0_input_length_temp_ce0;
wire    Loop_VITIS_LOOP_325_2_proc_U0_in_r_read;
wire    Loop_VITIS_LOOP_325_2_proc_U0_send_data_read;
wire    Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_flg_read;
wire   [7:0] Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_flg_din;
wire    Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_flg_write;
wire    Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_read;
wire   [12:0] Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_din;
wire    Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_write;
wire    Loop_VITIS_LOOP_325_2_proc_U0_inStream_in_read;
wire   [7:0] Loop_VITIS_LOOP_325_2_proc_U0_inStream_in_din;
wire    Loop_VITIS_LOOP_325_2_proc_U0_inStream_in_write;
wire    ap_sync_continue;
wire    input_length_temp_i_full_n;
wire    input_length_temp_t_empty_n;
wire    in_c_full_n;
wire   [63:0] in_c_dout;
wire    in_c_empty_n;
wire    input_length_c_full_n;
wire   [63:0] input_length_c_dout;
wire    input_length_c_empty_n;
wire    send_data_c_full_n;
wire   [63:0] send_data_c_dout;
wire    send_data_c_empty_n;
wire    send_data_c115_full_n;
wire   [63:0] send_data_c115_dout;
wire    send_data_c115_empty_n;
wire    output_length_c_full_n;
wire   [63:0] output_length_c_dout;
wire    output_length_c_empty_n;
wire   [7:0] num_chunks_loc_channel_dout;
wire    num_chunks_loc_channel_empty_n;
wire   [0:0] send_data_cast_loc_channel_dout;
wire    send_data_cast_loc_channel_empty_n;
wire   [63:0] p_loc_channel_dout;
wire    p_loc_channel_empty_n;
wire    outStream_code_flg_full_n;
wire   [7:0] outStream_code_flg_dout;
wire    outStream_code_flg_empty_n;
wire    outStream_code_full_n;
wire   [12:0] outStream_code_dout;
wire    outStream_code_empty_n;
wire    inStream_in_full_n;
wire   [7:0] inStream_in_dout;
wire    inStream_in_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_krnl_LZW_entry4_U0_ap_ready;
wire    ap_sync_krnl_LZW_entry4_U0_ap_ready;
reg    ap_sync_reg_Loop_VITIS_LOOP_318_1_proc_U0_ap_ready;
wire    ap_sync_Loop_VITIS_LOOP_318_1_proc_U0_ap_ready;
reg    ap_sync_reg_Loop_VITIS_LOOP_325_2_proc_U0_ap_ready;
wire    ap_sync_Loop_VITIS_LOOP_325_2_proc_U0_ap_ready;
wire   [0:0] start_for_Block_krnl_LZW_exit1_proc_U0_din;
wire    start_for_Block_krnl_LZW_exit1_proc_U0_full_n;
wire   [0:0] start_for_Block_krnl_LZW_exit1_proc_U0_dout;
wire    start_for_Block_krnl_LZW_exit1_proc_U0_empty_n;
wire    Loop_VITIS_LOOP_318_1_proc_U0_start_full_n;
wire    Loop_VITIS_LOOP_318_1_proc_U0_start_write;
wire    Block_krnl_LZW_exit1_proc_U0_start_full_n;
wire    Block_krnl_LZW_exit1_proc_U0_start_write;
wire    Loop_VITIS_LOOP_325_2_proc_U0_start_full_n;
wire    Loop_VITIS_LOOP_325_2_proc_U0_start_write;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_sync_reg_channel_write_num_chunks_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_input_length_temp = 1'b0;
#0 ap_sync_reg_channel_write_p_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_send_data_cast_loc_channel = 1'b0;
#0 ap_sync_reg_krnl_LZW_entry4_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Loop_VITIS_LOOP_318_1_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Loop_VITIS_LOOP_325_2_proc_U0_ap_ready = 1'b0;
end

krnl_LZW_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in_r(in_r),
    .input_length(input_length),
    .send_data(send_data),
    .output_length(output_length),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

krnl_LZW_aximm0_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 16 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_AXIMM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_AXIMM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_AXIMM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_AXIMM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_AXIMM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_AXIMM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_AXIMM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_AXIMM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_AXIMM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_AXIMM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_AXIMM0_CACHE_VALUE ))
aximm0_m_axi_U(
    .AWVALID(m_axi_aximm0_AWVALID),
    .AWREADY(m_axi_aximm0_AWREADY),
    .AWADDR(m_axi_aximm0_AWADDR),
    .AWID(m_axi_aximm0_AWID),
    .AWLEN(m_axi_aximm0_AWLEN),
    .AWSIZE(m_axi_aximm0_AWSIZE),
    .AWBURST(m_axi_aximm0_AWBURST),
    .AWLOCK(m_axi_aximm0_AWLOCK),
    .AWCACHE(m_axi_aximm0_AWCACHE),
    .AWPROT(m_axi_aximm0_AWPROT),
    .AWQOS(m_axi_aximm0_AWQOS),
    .AWREGION(m_axi_aximm0_AWREGION),
    .AWUSER(m_axi_aximm0_AWUSER),
    .WVALID(m_axi_aximm0_WVALID),
    .WREADY(m_axi_aximm0_WREADY),
    .WDATA(m_axi_aximm0_WDATA),
    .WSTRB(m_axi_aximm0_WSTRB),
    .WLAST(m_axi_aximm0_WLAST),
    .WID(m_axi_aximm0_WID),
    .WUSER(m_axi_aximm0_WUSER),
    .ARVALID(m_axi_aximm0_ARVALID),
    .ARREADY(m_axi_aximm0_ARREADY),
    .ARADDR(m_axi_aximm0_ARADDR),
    .ARID(m_axi_aximm0_ARID),
    .ARLEN(m_axi_aximm0_ARLEN),
    .ARSIZE(m_axi_aximm0_ARSIZE),
    .ARBURST(m_axi_aximm0_ARBURST),
    .ARLOCK(m_axi_aximm0_ARLOCK),
    .ARCACHE(m_axi_aximm0_ARCACHE),
    .ARPROT(m_axi_aximm0_ARPROT),
    .ARQOS(m_axi_aximm0_ARQOS),
    .ARREGION(m_axi_aximm0_ARREGION),
    .ARUSER(m_axi_aximm0_ARUSER),
    .RVALID(m_axi_aximm0_RVALID),
    .RREADY(m_axi_aximm0_RREADY),
    .RDATA(m_axi_aximm0_RDATA),
    .RLAST(m_axi_aximm0_RLAST),
    .RID(m_axi_aximm0_RID),
    .RUSER(m_axi_aximm0_RUSER),
    .RRESP(m_axi_aximm0_RRESP),
    .BVALID(m_axi_aximm0_BVALID),
    .BREADY(m_axi_aximm0_BREADY),
    .BRESP(m_axi_aximm0_BRESP),
    .BID(m_axi_aximm0_BID),
    .BUSER(m_axi_aximm0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARVALID),
    .I_ARREADY(aximm0_ARREADY),
    .I_ARADDR(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARADDR),
    .I_ARID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARID),
    .I_ARLEN(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARLEN),
    .I_ARSIZE(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARSIZE),
    .I_ARLOCK(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARLOCK),
    .I_ARCACHE(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARCACHE),
    .I_ARQOS(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARQOS),
    .I_ARPROT(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARPROT),
    .I_ARUSER(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARUSER),
    .I_ARBURST(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARBURST),
    .I_ARREGION(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARREGION),
    .I_RVALID(aximm0_RVALID),
    .I_RREADY(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_RREADY),
    .I_RDATA(aximm0_RDATA),
    .I_RID(aximm0_RID),
    .I_RUSER(aximm0_RUSER),
    .I_RRESP(aximm0_RRESP),
    .I_RLAST(aximm0_RLAST),
    .I_AWVALID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWVALID),
    .I_AWREADY(aximm0_AWREADY),
    .I_AWADDR(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWADDR),
    .I_AWID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWID),
    .I_AWLEN(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWLEN),
    .I_AWSIZE(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWSIZE),
    .I_AWLOCK(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWLOCK),
    .I_AWCACHE(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWCACHE),
    .I_AWQOS(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWQOS),
    .I_AWPROT(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWPROT),
    .I_AWUSER(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWUSER),
    .I_AWBURST(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWBURST),
    .I_AWREGION(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWREGION),
    .I_WVALID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WVALID),
    .I_WREADY(aximm0_WREADY),
    .I_WDATA(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WDATA),
    .I_WID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WID),
    .I_WUSER(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WUSER),
    .I_WLAST(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WLAST),
    .I_WSTRB(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WSTRB),
    .I_BVALID(aximm0_BVALID),
    .I_BREADY(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_BREADY),
    .I_BRESP(aximm0_BRESP),
    .I_BID(aximm0_BID),
    .I_BUSER(aximm0_BUSER)
);

krnl_LZW_aximm1_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 16 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_AXIMM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_AXIMM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_AXIMM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_AXIMM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_AXIMM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_AXIMM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_AXIMM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_AXIMM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_AXIMM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_AXIMM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_AXIMM1_CACHE_VALUE ))
aximm1_m_axi_U(
    .AWVALID(m_axi_aximm1_AWVALID),
    .AWREADY(m_axi_aximm1_AWREADY),
    .AWADDR(m_axi_aximm1_AWADDR),
    .AWID(m_axi_aximm1_AWID),
    .AWLEN(m_axi_aximm1_AWLEN),
    .AWSIZE(m_axi_aximm1_AWSIZE),
    .AWBURST(m_axi_aximm1_AWBURST),
    .AWLOCK(m_axi_aximm1_AWLOCK),
    .AWCACHE(m_axi_aximm1_AWCACHE),
    .AWPROT(m_axi_aximm1_AWPROT),
    .AWQOS(m_axi_aximm1_AWQOS),
    .AWREGION(m_axi_aximm1_AWREGION),
    .AWUSER(m_axi_aximm1_AWUSER),
    .WVALID(m_axi_aximm1_WVALID),
    .WREADY(m_axi_aximm1_WREADY),
    .WDATA(m_axi_aximm1_WDATA),
    .WSTRB(m_axi_aximm1_WSTRB),
    .WLAST(m_axi_aximm1_WLAST),
    .WID(m_axi_aximm1_WID),
    .WUSER(m_axi_aximm1_WUSER),
    .ARVALID(m_axi_aximm1_ARVALID),
    .ARREADY(m_axi_aximm1_ARREADY),
    .ARADDR(m_axi_aximm1_ARADDR),
    .ARID(m_axi_aximm1_ARID),
    .ARLEN(m_axi_aximm1_ARLEN),
    .ARSIZE(m_axi_aximm1_ARSIZE),
    .ARBURST(m_axi_aximm1_ARBURST),
    .ARLOCK(m_axi_aximm1_ARLOCK),
    .ARCACHE(m_axi_aximm1_ARCACHE),
    .ARPROT(m_axi_aximm1_ARPROT),
    .ARQOS(m_axi_aximm1_ARQOS),
    .ARREGION(m_axi_aximm1_ARREGION),
    .ARUSER(m_axi_aximm1_ARUSER),
    .RVALID(m_axi_aximm1_RVALID),
    .RREADY(m_axi_aximm1_RREADY),
    .RDATA(m_axi_aximm1_RDATA),
    .RLAST(m_axi_aximm1_RLAST),
    .RID(m_axi_aximm1_RID),
    .RUSER(m_axi_aximm1_RUSER),
    .RRESP(m_axi_aximm1_RRESP),
    .BVALID(m_axi_aximm1_BVALID),
    .BREADY(m_axi_aximm1_BREADY),
    .BRESP(m_axi_aximm1_BRESP),
    .BID(m_axi_aximm1_BID),
    .BUSER(m_axi_aximm1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARVALID),
    .I_ARREADY(aximm1_ARREADY),
    .I_ARADDR(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARADDR),
    .I_ARID(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARID),
    .I_ARLEN(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARLEN),
    .I_ARSIZE(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARSIZE),
    .I_ARLOCK(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARLOCK),
    .I_ARCACHE(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARCACHE),
    .I_ARQOS(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARQOS),
    .I_ARPROT(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARPROT),
    .I_ARUSER(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARUSER),
    .I_ARBURST(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARBURST),
    .I_ARREGION(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARREGION),
    .I_RVALID(aximm1_RVALID),
    .I_RREADY(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_RREADY),
    .I_RDATA(aximm1_RDATA),
    .I_RID(aximm1_RID),
    .I_RUSER(aximm1_RUSER),
    .I_RRESP(aximm1_RRESP),
    .I_RLAST(aximm1_RLAST),
    .I_AWVALID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWVALID),
    .I_AWREADY(aximm1_AWREADY),
    .I_AWADDR(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWADDR),
    .I_AWID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWID),
    .I_AWLEN(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWLEN),
    .I_AWSIZE(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWSIZE),
    .I_AWLOCK(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWLOCK),
    .I_AWCACHE(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWCACHE),
    .I_AWQOS(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWQOS),
    .I_AWPROT(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWPROT),
    .I_AWUSER(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWUSER),
    .I_AWBURST(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWBURST),
    .I_AWREGION(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWREGION),
    .I_WVALID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WVALID),
    .I_WREADY(aximm1_WREADY),
    .I_WDATA(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WDATA),
    .I_WID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WID),
    .I_WUSER(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WUSER),
    .I_WLAST(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WLAST),
    .I_WSTRB(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WSTRB),
    .I_BVALID(aximm1_BVALID),
    .I_BREADY(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_BREADY),
    .I_BRESP(aximm1_BRESP),
    .I_BID(aximm1_BID),
    .I_BUSER(aximm1_BUSER)
);

krnl_LZW_store_array_i #(
    .DataWidth( 16 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
store_array_i_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_address0),
    .ce0(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_ce0),
    .we0(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_we0),
    .d0(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_d0),
    .q0(store_array_i_q0),
    .address1(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_address1),
    .ce1(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_ce1),
    .we1(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_we1),
    .d1(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_d1),
    .q1(store_array_i_q1)
);

krnl_LZW_input_length_temp #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
input_length_temp_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_address0),
    .i_ce0(Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_ce0),
    .i_we0(Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_we0),
    .i_d0(Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_d0),
    .i_q0(input_length_temp_i_q0),
    .t_address0(Loop_VITIS_LOOP_325_2_proc_U0_input_length_temp_address0),
    .t_ce0(Loop_VITIS_LOOP_325_2_proc_U0_input_length_temp_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(input_length_temp_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(input_length_temp_i_full_n),
    .i_write(ap_channel_done_input_length_temp),
    .t_empty_n(input_length_temp_t_empty_n),
    .t_read(Loop_VITIS_LOOP_325_2_proc_U0_ap_ready)
);

krnl_LZW_krnl_LZW_entry4 krnl_LZW_entry4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(krnl_LZW_entry4_U0_ap_start),
    .start_full_n(start_for_Block_krnl_LZW_exit1_proc_U0_full_n),
    .ap_done(krnl_LZW_entry4_U0_ap_done),
    .ap_continue(krnl_LZW_entry4_U0_ap_continue),
    .ap_idle(krnl_LZW_entry4_U0_ap_idle),
    .ap_ready(krnl_LZW_entry4_U0_ap_ready),
    .start_out(krnl_LZW_entry4_U0_start_out),
    .start_write(krnl_LZW_entry4_U0_start_write),
    .in_r(in_r),
    .input_length(input_length),
    .send_data(send_data),
    .output_length(output_length),
    .in_out_din(krnl_LZW_entry4_U0_in_out_din),
    .in_out_full_n(in_c_full_n),
    .in_out_write(krnl_LZW_entry4_U0_in_out_write),
    .input_length_out_din(krnl_LZW_entry4_U0_input_length_out_din),
    .input_length_out_full_n(input_length_c_full_n),
    .input_length_out_write(krnl_LZW_entry4_U0_input_length_out_write),
    .send_data_out_din(krnl_LZW_entry4_U0_send_data_out_din),
    .send_data_out_full_n(send_data_c_full_n),
    .send_data_out_write(krnl_LZW_entry4_U0_send_data_out_write),
    .send_data_out1_din(krnl_LZW_entry4_U0_send_data_out1_din),
    .send_data_out1_full_n(send_data_c115_full_n),
    .send_data_out1_write(krnl_LZW_entry4_U0_send_data_out1_write),
    .output_length_out_din(krnl_LZW_entry4_U0_output_length_out_din),
    .output_length_out_full_n(output_length_c_full_n),
    .output_length_out_write(krnl_LZW_entry4_U0_output_length_out_write)
);

krnl_LZW_Loop_VITIS_LOOP_318_1_proc Loop_VITIS_LOOP_318_1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VITIS_LOOP_318_1_proc_U0_ap_start),
    .ap_done(Loop_VITIS_LOOP_318_1_proc_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_318_1_proc_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_318_1_proc_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_318_1_proc_U0_ap_ready),
    .input_length_temp_address0(Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_address0),
    .input_length_temp_ce0(Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_ce0),
    .input_length_temp_we0(Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_we0),
    .input_length_temp_d0(Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_d0),
    .input_length_dout(input_length_c_dout),
    .input_length_empty_n(input_length_c_empty_n),
    .input_length_read(Loop_VITIS_LOOP_318_1_proc_U0_input_length_read),
    .m_axi_aximm1_AWVALID(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWVALID),
    .m_axi_aximm1_AWREADY(1'b0),
    .m_axi_aximm1_AWADDR(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWADDR),
    .m_axi_aximm1_AWID(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWID),
    .m_axi_aximm1_AWLEN(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWLEN),
    .m_axi_aximm1_AWSIZE(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWSIZE),
    .m_axi_aximm1_AWBURST(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWBURST),
    .m_axi_aximm1_AWLOCK(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWLOCK),
    .m_axi_aximm1_AWCACHE(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWCACHE),
    .m_axi_aximm1_AWPROT(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWPROT),
    .m_axi_aximm1_AWQOS(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWQOS),
    .m_axi_aximm1_AWREGION(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWREGION),
    .m_axi_aximm1_AWUSER(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_AWUSER),
    .m_axi_aximm1_WVALID(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_WVALID),
    .m_axi_aximm1_WREADY(1'b0),
    .m_axi_aximm1_WDATA(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_WDATA),
    .m_axi_aximm1_WSTRB(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_WSTRB),
    .m_axi_aximm1_WLAST(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_WLAST),
    .m_axi_aximm1_WID(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_WID),
    .m_axi_aximm1_WUSER(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_WUSER),
    .m_axi_aximm1_ARVALID(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARVALID),
    .m_axi_aximm1_ARREADY(aximm1_ARREADY),
    .m_axi_aximm1_ARADDR(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARADDR),
    .m_axi_aximm1_ARID(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARID),
    .m_axi_aximm1_ARLEN(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARLEN),
    .m_axi_aximm1_ARSIZE(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARSIZE),
    .m_axi_aximm1_ARBURST(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARBURST),
    .m_axi_aximm1_ARLOCK(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARLOCK),
    .m_axi_aximm1_ARCACHE(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARCACHE),
    .m_axi_aximm1_ARPROT(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARPROT),
    .m_axi_aximm1_ARQOS(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARQOS),
    .m_axi_aximm1_ARREGION(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARREGION),
    .m_axi_aximm1_ARUSER(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_ARUSER),
    .m_axi_aximm1_RVALID(aximm1_RVALID),
    .m_axi_aximm1_RREADY(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_RREADY),
    .m_axi_aximm1_RDATA(aximm1_RDATA),
    .m_axi_aximm1_RLAST(aximm1_RLAST),
    .m_axi_aximm1_RID(aximm1_RID),
    .m_axi_aximm1_RUSER(aximm1_RUSER),
    .m_axi_aximm1_RRESP(aximm1_RRESP),
    .m_axi_aximm1_BVALID(1'b0),
    .m_axi_aximm1_BREADY(Loop_VITIS_LOOP_318_1_proc_U0_m_axi_aximm1_BREADY),
    .m_axi_aximm1_BRESP(2'd0),
    .m_axi_aximm1_BID(1'd0),
    .m_axi_aximm1_BUSER(1'd0),
    .ap_return(Loop_VITIS_LOOP_318_1_proc_U0_ap_return)
);

krnl_LZW_Block_krnl_LZW_exit1_proc Block_krnl_LZW_exit1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_krnl_LZW_exit1_proc_U0_ap_start),
    .ap_done(Block_krnl_LZW_exit1_proc_U0_ap_done),
    .ap_continue(Block_krnl_LZW_exit1_proc_U0_ap_continue),
    .ap_idle(Block_krnl_LZW_exit1_proc_U0_ap_idle),
    .ap_ready(Block_krnl_LZW_exit1_proc_U0_ap_ready),
    .send_data_dout(send_data_c_dout),
    .send_data_empty_n(send_data_c_empty_n),
    .send_data_read(Block_krnl_LZW_exit1_proc_U0_send_data_read),
    .ap_return_0(Block_krnl_LZW_exit1_proc_U0_ap_return_0),
    .ap_return_1(Block_krnl_LZW_exit1_proc_U0_ap_return_1)
);

krnl_LZW_Loop_VITIS_LOOP_325_2_proc Loop_VITIS_LOOP_325_2_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VITIS_LOOP_325_2_proc_U0_ap_start),
    .ap_done(Loop_VITIS_LOOP_325_2_proc_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_325_2_proc_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_325_2_proc_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_325_2_proc_U0_ap_ready),
    .p_read(num_chunks_loc_channel_dout),
    .m_axi_aximm0_AWVALID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWVALID),
    .m_axi_aximm0_AWREADY(aximm0_AWREADY),
    .m_axi_aximm0_AWADDR(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWADDR),
    .m_axi_aximm0_AWID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWID),
    .m_axi_aximm0_AWLEN(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWLEN),
    .m_axi_aximm0_AWSIZE(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWSIZE),
    .m_axi_aximm0_AWBURST(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWBURST),
    .m_axi_aximm0_AWLOCK(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWLOCK),
    .m_axi_aximm0_AWCACHE(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWCACHE),
    .m_axi_aximm0_AWPROT(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWPROT),
    .m_axi_aximm0_AWQOS(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWQOS),
    .m_axi_aximm0_AWREGION(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWREGION),
    .m_axi_aximm0_AWUSER(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_AWUSER),
    .m_axi_aximm0_WVALID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WVALID),
    .m_axi_aximm0_WREADY(aximm0_WREADY),
    .m_axi_aximm0_WDATA(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WDATA),
    .m_axi_aximm0_WSTRB(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WSTRB),
    .m_axi_aximm0_WLAST(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WLAST),
    .m_axi_aximm0_WID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WID),
    .m_axi_aximm0_WUSER(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_WUSER),
    .m_axi_aximm0_ARVALID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARVALID),
    .m_axi_aximm0_ARREADY(aximm0_ARREADY),
    .m_axi_aximm0_ARADDR(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARADDR),
    .m_axi_aximm0_ARID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARID),
    .m_axi_aximm0_ARLEN(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARLEN),
    .m_axi_aximm0_ARSIZE(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARSIZE),
    .m_axi_aximm0_ARBURST(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARBURST),
    .m_axi_aximm0_ARLOCK(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARLOCK),
    .m_axi_aximm0_ARCACHE(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARCACHE),
    .m_axi_aximm0_ARPROT(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARPROT),
    .m_axi_aximm0_ARQOS(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARQOS),
    .m_axi_aximm0_ARREGION(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARREGION),
    .m_axi_aximm0_ARUSER(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_ARUSER),
    .m_axi_aximm0_RVALID(aximm0_RVALID),
    .m_axi_aximm0_RREADY(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_RREADY),
    .m_axi_aximm0_RDATA(aximm0_RDATA),
    .m_axi_aximm0_RLAST(aximm0_RLAST),
    .m_axi_aximm0_RID(aximm0_RID),
    .m_axi_aximm0_RUSER(aximm0_RUSER),
    .m_axi_aximm0_RRESP(aximm0_RRESP),
    .m_axi_aximm0_BVALID(aximm0_BVALID),
    .m_axi_aximm0_BREADY(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm0_BREADY),
    .m_axi_aximm0_BRESP(aximm0_BRESP),
    .m_axi_aximm0_BID(aximm0_BID),
    .m_axi_aximm0_BUSER(aximm0_BUSER),
    .store_array_i_address0(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_address0),
    .store_array_i_ce0(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_ce0),
    .store_array_i_we0(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_we0),
    .store_array_i_d0(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_d0),
    .store_array_i_q0(store_array_i_q0),
    .store_array_i_address1(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_address1),
    .store_array_i_ce1(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_ce1),
    .store_array_i_we1(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_we1),
    .store_array_i_d1(Loop_VITIS_LOOP_325_2_proc_U0_store_array_i_d1),
    .store_array_i_q1(store_array_i_q1),
    .p_read1(p_loc_channel_dout),
    .p_read2(send_data_cast_loc_channel_dout),
    .m_axi_aximm1_AWVALID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWVALID),
    .m_axi_aximm1_AWREADY(aximm1_AWREADY),
    .m_axi_aximm1_AWADDR(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWADDR),
    .m_axi_aximm1_AWID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWID),
    .m_axi_aximm1_AWLEN(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWLEN),
    .m_axi_aximm1_AWSIZE(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWSIZE),
    .m_axi_aximm1_AWBURST(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWBURST),
    .m_axi_aximm1_AWLOCK(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWLOCK),
    .m_axi_aximm1_AWCACHE(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWCACHE),
    .m_axi_aximm1_AWPROT(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWPROT),
    .m_axi_aximm1_AWQOS(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWQOS),
    .m_axi_aximm1_AWREGION(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWREGION),
    .m_axi_aximm1_AWUSER(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_AWUSER),
    .m_axi_aximm1_WVALID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WVALID),
    .m_axi_aximm1_WREADY(aximm1_WREADY),
    .m_axi_aximm1_WDATA(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WDATA),
    .m_axi_aximm1_WSTRB(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WSTRB),
    .m_axi_aximm1_WLAST(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WLAST),
    .m_axi_aximm1_WID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WID),
    .m_axi_aximm1_WUSER(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_WUSER),
    .m_axi_aximm1_ARVALID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARVALID),
    .m_axi_aximm1_ARREADY(1'b0),
    .m_axi_aximm1_ARADDR(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARADDR),
    .m_axi_aximm1_ARID(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARID),
    .m_axi_aximm1_ARLEN(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARLEN),
    .m_axi_aximm1_ARSIZE(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARSIZE),
    .m_axi_aximm1_ARBURST(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARBURST),
    .m_axi_aximm1_ARLOCK(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARLOCK),
    .m_axi_aximm1_ARCACHE(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARCACHE),
    .m_axi_aximm1_ARPROT(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARPROT),
    .m_axi_aximm1_ARQOS(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARQOS),
    .m_axi_aximm1_ARREGION(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARREGION),
    .m_axi_aximm1_ARUSER(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_ARUSER),
    .m_axi_aximm1_RVALID(1'b0),
    .m_axi_aximm1_RREADY(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_RREADY),
    .m_axi_aximm1_RDATA(16'd0),
    .m_axi_aximm1_RLAST(1'b0),
    .m_axi_aximm1_RID(1'd0),
    .m_axi_aximm1_RUSER(1'd0),
    .m_axi_aximm1_RRESP(2'd0),
    .m_axi_aximm1_BVALID(aximm1_BVALID),
    .m_axi_aximm1_BREADY(Loop_VITIS_LOOP_325_2_proc_U0_m_axi_aximm1_BREADY),
    .m_axi_aximm1_BRESP(aximm1_BRESP),
    .m_axi_aximm1_BID(aximm1_BID),
    .m_axi_aximm1_BUSER(aximm1_BUSER),
    .output_length_dout(output_length_c_dout),
    .output_length_empty_n(output_length_c_empty_n),
    .output_length_read(Loop_VITIS_LOOP_325_2_proc_U0_output_length_read),
    .input_length_temp_address0(Loop_VITIS_LOOP_325_2_proc_U0_input_length_temp_address0),
    .input_length_temp_ce0(Loop_VITIS_LOOP_325_2_proc_U0_input_length_temp_ce0),
    .input_length_temp_q0(input_length_temp_t_q0),
    .in_r_dout(in_c_dout),
    .in_r_empty_n(in_c_empty_n),
    .in_r_read(Loop_VITIS_LOOP_325_2_proc_U0_in_r_read),
    .send_data_dout(send_data_c115_dout),
    .send_data_empty_n(send_data_c115_empty_n),
    .send_data_read(Loop_VITIS_LOOP_325_2_proc_U0_send_data_read),
    .outStream_code_flg_dout(outStream_code_flg_dout),
    .outStream_code_flg_empty_n(outStream_code_flg_empty_n),
    .outStream_code_flg_read(Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_flg_read),
    .outStream_code_flg_din(Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_flg_din),
    .outStream_code_flg_full_n(outStream_code_flg_full_n),
    .outStream_code_flg_write(Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_flg_write),
    .outStream_code_dout(outStream_code_dout),
    .outStream_code_empty_n(outStream_code_empty_n),
    .outStream_code_read(Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_read),
    .outStream_code_din(Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_din),
    .outStream_code_full_n(outStream_code_full_n),
    .outStream_code_write(Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_write),
    .inStream_in_dout(inStream_in_dout),
    .inStream_in_empty_n(inStream_in_empty_n),
    .inStream_in_read(Loop_VITIS_LOOP_325_2_proc_U0_inStream_in_read),
    .inStream_in_din(Loop_VITIS_LOOP_325_2_proc_U0_inStream_in_din),
    .inStream_in_full_n(inStream_in_full_n),
    .inStream_in_write(Loop_VITIS_LOOP_325_2_proc_U0_inStream_in_write)
);

krnl_LZW_fifo_w64_d3_S in_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(krnl_LZW_entry4_U0_in_out_din),
    .if_full_n(in_c_full_n),
    .if_write(krnl_LZW_entry4_U0_in_out_write),
    .if_dout(in_c_dout),
    .if_empty_n(in_c_empty_n),
    .if_read(Loop_VITIS_LOOP_325_2_proc_U0_in_r_read)
);

krnl_LZW_fifo_w64_d2_S input_length_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(krnl_LZW_entry4_U0_input_length_out_din),
    .if_full_n(input_length_c_full_n),
    .if_write(krnl_LZW_entry4_U0_input_length_out_write),
    .if_dout(input_length_c_dout),
    .if_empty_n(input_length_c_empty_n),
    .if_read(Loop_VITIS_LOOP_318_1_proc_U0_input_length_read)
);

krnl_LZW_fifo_w64_d2_S send_data_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(krnl_LZW_entry4_U0_send_data_out_din),
    .if_full_n(send_data_c_full_n),
    .if_write(krnl_LZW_entry4_U0_send_data_out_write),
    .if_dout(send_data_c_dout),
    .if_empty_n(send_data_c_empty_n),
    .if_read(Block_krnl_LZW_exit1_proc_U0_send_data_read)
);

krnl_LZW_fifo_w64_d3_S send_data_c115_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(krnl_LZW_entry4_U0_send_data_out1_din),
    .if_full_n(send_data_c115_full_n),
    .if_write(krnl_LZW_entry4_U0_send_data_out1_write),
    .if_dout(send_data_c115_dout),
    .if_empty_n(send_data_c115_empty_n),
    .if_read(Loop_VITIS_LOOP_325_2_proc_U0_send_data_read)
);

krnl_LZW_fifo_w64_d3_S output_length_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(krnl_LZW_entry4_U0_output_length_out_din),
    .if_full_n(output_length_c_full_n),
    .if_write(krnl_LZW_entry4_U0_output_length_out_write),
    .if_dout(output_length_c_dout),
    .if_empty_n(output_length_c_empty_n),
    .if_read(Loop_VITIS_LOOP_325_2_proc_U0_output_length_read)
);

krnl_LZW_fifo_w8_d2_S num_chunks_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VITIS_LOOP_318_1_proc_U0_ap_return),
    .if_full_n(num_chunks_loc_channel_full_n),
    .if_write(ap_channel_done_num_chunks_loc_channel),
    .if_dout(num_chunks_loc_channel_dout),
    .if_empty_n(num_chunks_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_325_2_proc_U0_ap_ready)
);

krnl_LZW_fifo_w1_d2_S send_data_cast_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_krnl_LZW_exit1_proc_U0_ap_return_0),
    .if_full_n(send_data_cast_loc_channel_full_n),
    .if_write(ap_channel_done_send_data_cast_loc_channel),
    .if_dout(send_data_cast_loc_channel_dout),
    .if_empty_n(send_data_cast_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_325_2_proc_U0_ap_ready)
);

krnl_LZW_fifo_w64_d2_S p_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_krnl_LZW_exit1_proc_U0_ap_return_1),
    .if_full_n(p_loc_channel_full_n),
    .if_write(ap_channel_done_p_loc_channel),
    .if_dout(p_loc_channel_dout),
    .if_empty_n(p_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_325_2_proc_U0_ap_ready)
);

krnl_LZW_fifo_w8_d2_S outStream_code_flg_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_flg_din),
    .if_full_n(outStream_code_flg_full_n),
    .if_write(Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_flg_write),
    .if_dout(outStream_code_flg_dout),
    .if_empty_n(outStream_code_flg_empty_n),
    .if_read(Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_flg_read)
);

krnl_LZW_fifo_w13_d2_S outStream_code_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_din),
    .if_full_n(outStream_code_full_n),
    .if_write(Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_write),
    .if_dout(outStream_code_dout),
    .if_empty_n(outStream_code_empty_n),
    .if_read(Loop_VITIS_LOOP_325_2_proc_U0_outStream_code_read)
);

krnl_LZW_fifo_w8_d2_S inStream_in_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VITIS_LOOP_325_2_proc_U0_inStream_in_din),
    .if_full_n(inStream_in_full_n),
    .if_write(Loop_VITIS_LOOP_325_2_proc_U0_inStream_in_write),
    .if_dout(inStream_in_dout),
    .if_empty_n(inStream_in_empty_n),
    .if_read(Loop_VITIS_LOOP_325_2_proc_U0_inStream_in_read)
);

krnl_LZW_start_for_Block_krnl_LZW_exit1_proc_U0 start_for_Block_krnl_LZW_exit1_proc_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Block_krnl_LZW_exit1_proc_U0_din),
    .if_full_n(start_for_Block_krnl_LZW_exit1_proc_U0_full_n),
    .if_write(krnl_LZW_entry4_U0_start_write),
    .if_dout(start_for_Block_krnl_LZW_exit1_proc_U0_dout),
    .if_empty_n(start_for_Block_krnl_LZW_exit1_proc_U0_empty_n),
    .if_read(Block_krnl_LZW_exit1_proc_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Loop_VITIS_LOOP_318_1_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Loop_VITIS_LOOP_318_1_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Loop_VITIS_LOOP_318_1_proc_U0_ap_ready <= ap_sync_Loop_VITIS_LOOP_318_1_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Loop_VITIS_LOOP_325_2_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Loop_VITIS_LOOP_325_2_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Loop_VITIS_LOOP_325_2_proc_U0_ap_ready <= ap_sync_Loop_VITIS_LOOP_325_2_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_input_length_temp <= 1'b0;
    end else begin
        if (((Loop_VITIS_LOOP_318_1_proc_U0_ap_done & Loop_VITIS_LOOP_318_1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_input_length_temp <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_input_length_temp <= ap_sync_channel_write_input_length_temp;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_num_chunks_loc_channel <= 1'b0;
    end else begin
        if (((Loop_VITIS_LOOP_318_1_proc_U0_ap_done & Loop_VITIS_LOOP_318_1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_num_chunks_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_num_chunks_loc_channel <= ap_sync_channel_write_num_chunks_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_p_loc_channel <= 1'b0;
    end else begin
        if (((Block_krnl_LZW_exit1_proc_U0_ap_done & Block_krnl_LZW_exit1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_p_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_p_loc_channel <= ap_sync_channel_write_p_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_send_data_cast_loc_channel <= 1'b0;
    end else begin
        if (((Block_krnl_LZW_exit1_proc_U0_ap_done & Block_krnl_LZW_exit1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_send_data_cast_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_send_data_cast_loc_channel <= ap_sync_channel_write_send_data_cast_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_krnl_LZW_entry4_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_krnl_LZW_entry4_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_krnl_LZW_entry4_U0_ap_ready <= ap_sync_krnl_LZW_entry4_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

assign Block_krnl_LZW_exit1_proc_U0_ap_continue = (ap_sync_channel_write_send_data_cast_loc_channel & ap_sync_channel_write_p_loc_channel);

assign Block_krnl_LZW_exit1_proc_U0_ap_start = start_for_Block_krnl_LZW_exit1_proc_U0_empty_n;

assign Block_krnl_LZW_exit1_proc_U0_start_full_n = 1'b1;

assign Block_krnl_LZW_exit1_proc_U0_start_write = 1'b0;

assign Loop_VITIS_LOOP_318_1_proc_U0_ap_continue = (ap_sync_channel_write_num_chunks_loc_channel & ap_sync_channel_write_input_length_temp);

assign Loop_VITIS_LOOP_318_1_proc_U0_ap_start = ((ap_sync_reg_Loop_VITIS_LOOP_318_1_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_full_n = input_length_temp_i_full_n;

assign Loop_VITIS_LOOP_318_1_proc_U0_start_full_n = 1'b1;

assign Loop_VITIS_LOOP_318_1_proc_U0_start_write = 1'b0;

assign Loop_VITIS_LOOP_325_2_proc_U0_ap_continue = ap_continue;

assign Loop_VITIS_LOOP_325_2_proc_U0_ap_start = (send_data_cast_loc_channel_empty_n & p_loc_channel_empty_n & num_chunks_loc_channel_empty_n & input_length_temp_t_empty_n & (ap_sync_reg_Loop_VITIS_LOOP_325_2_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign Loop_VITIS_LOOP_325_2_proc_U0_start_full_n = 1'b1;

assign Loop_VITIS_LOOP_325_2_proc_U0_start_write = 1'b0;

assign ap_channel_done_input_length_temp = ((ap_sync_reg_channel_write_input_length_temp ^ 1'b1) & Loop_VITIS_LOOP_318_1_proc_U0_ap_done);

assign ap_channel_done_num_chunks_loc_channel = ((ap_sync_reg_channel_write_num_chunks_loc_channel ^ 1'b1) & Loop_VITIS_LOOP_318_1_proc_U0_ap_done);

assign ap_channel_done_p_loc_channel = ((ap_sync_reg_channel_write_p_loc_channel ^ 1'b1) & Block_krnl_LZW_exit1_proc_U0_ap_done);

assign ap_channel_done_send_data_cast_loc_channel = ((ap_sync_reg_channel_write_send_data_cast_loc_channel ^ 1'b1) & Block_krnl_LZW_exit1_proc_U0_ap_done);

assign ap_done = Loop_VITIS_LOOP_325_2_proc_U0_ap_done;

assign ap_idle = (krnl_LZW_entry4_U0_ap_idle & (p_loc_channel_empty_n ^ 1'b1) & (send_data_cast_loc_channel_empty_n ^ 1'b1) & (num_chunks_loc_channel_empty_n ^ 1'b1) & (input_length_temp_t_empty_n ^ 1'b1) & Loop_VITIS_LOOP_325_2_proc_U0_ap_idle & Loop_VITIS_LOOP_318_1_proc_U0_ap_idle & Block_krnl_LZW_exit1_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_Loop_VITIS_LOOP_318_1_proc_U0_ap_ready = (ap_sync_reg_Loop_VITIS_LOOP_318_1_proc_U0_ap_ready | Loop_VITIS_LOOP_318_1_proc_U0_ap_ready);

assign ap_sync_Loop_VITIS_LOOP_325_2_proc_U0_ap_ready = (ap_sync_reg_Loop_VITIS_LOOP_325_2_proc_U0_ap_ready | Loop_VITIS_LOOP_325_2_proc_U0_ap_ready);

assign ap_sync_channel_write_input_length_temp = ((ap_channel_done_input_length_temp & Loop_VITIS_LOOP_318_1_proc_U0_input_length_temp_full_n) | ap_sync_reg_channel_write_input_length_temp);

assign ap_sync_channel_write_num_chunks_loc_channel = ((num_chunks_loc_channel_full_n & ap_channel_done_num_chunks_loc_channel) | ap_sync_reg_channel_write_num_chunks_loc_channel);

assign ap_sync_channel_write_p_loc_channel = ((p_loc_channel_full_n & ap_channel_done_p_loc_channel) | ap_sync_reg_channel_write_p_loc_channel);

assign ap_sync_channel_write_send_data_cast_loc_channel = ((send_data_cast_loc_channel_full_n & ap_channel_done_send_data_cast_loc_channel) | ap_sync_reg_channel_write_send_data_cast_loc_channel);

assign ap_sync_continue = ap_continue;

assign ap_sync_done = Loop_VITIS_LOOP_325_2_proc_U0_ap_done;

assign ap_sync_krnl_LZW_entry4_U0_ap_ready = (krnl_LZW_entry4_U0_ap_ready | ap_sync_reg_krnl_LZW_entry4_U0_ap_ready);

assign ap_sync_ready = (ap_sync_krnl_LZW_entry4_U0_ap_ready & ap_sync_Loop_VITIS_LOOP_325_2_proc_U0_ap_ready & ap_sync_Loop_VITIS_LOOP_318_1_proc_U0_ap_ready);

assign krnl_LZW_entry4_U0_ap_continue = 1'b1;

assign krnl_LZW_entry4_U0_ap_start = ((ap_sync_reg_krnl_LZW_entry4_U0_ap_ready ^ 1'b1) & ap_start);

assign start_for_Block_krnl_LZW_exit1_proc_U0_din = 1'b1;

endmodule //krnl_LZW
